[metadata]
name = product-data-hub-client
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description = Clients for Product Data Hub APIs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/product-data-hub-client

[options]
python_requires = ~=3.7
include_package_data = True
packages =
	product_data_hub_client
	product_data_hub_client.abc
	product_data_hub_client.material_management
	product_data_hub_client.line_management
	product_data_hub_client.material_vendor_management
	product_data_hub_client.product_development
	product_data_hub_client.material_sustainability
install_requires =
	sob~=1.50
	cerberus-assistant~=1.0
	oapi~=1.62

[options.package_data]
* = py.typed
