[tox]
envlist = pytest, isort, black, flake8, mypy

[testenv]
install_command =
	python3 -m pip install -c requirements.txt {opts} {packages}
passenv =
	USER
	HOME
	HUDSON_URL
	CI
	AWS_WEB_IDENTITY_TOKEN_FILE
	AWS_ROLE_ARN
	DOCKER_*
setenv =
	PIP_EXTRA_INDEX_URL =

[testenv:pytest]
deps =
	pytest
	pyspark
commands =
	py.test

[testenv:black]
deps =
	black
commands =
	black --check .

[testenv:isort]
deps =
	isort
commands =
	isort -c .

[testenv:flake8]
deps =
	flake8
commands =
	flake8

[testenv:mypy]
deps =
	mypy
	pyspark
	daves-dev-tools
commands =
	mypy --install-types --non-interactive
	mypy
