name: test
on:
  workflow_dispatch:
  pull_request:
    branches:
    - '*'
    paths:
    - map-airflow-client/**
    - setup.py
    - setup.cfg
    - tests/**
    - requirements.txt
    - tox.ini
    - .github/**
jobs:
  test:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        python:
        - 3.8
        - 3.9
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - run: make ci-install
    - run: make test
