[metadata]
name = {{cookiecutter.name}}
version = 0.0.0
author_email = {{cookiecutter.author_email}}
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/{{cookiecutter.name}}

[options]
python_requires = {{cookiecutter.python_requires}}
include_package_data = True
packages =
	{{cookiecutter.package}}

[options.entry_points]
console_scripts =
	{{cookiecutter.name}} = {{cookiecutter.package}}.__main__:main

[options.package_data]
* = py.typed
