[metadata]
name = analytics-orm
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = Object Relational Mapper
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/analytics-orm

[options]
python_requires = ~=3.8
packages =
	analytics_orm
	analytics_orm.alembic
include_package_data = True
install_requires =
	sqlalchemy<3.0.0,>=1.4.51
	cerberus-python-client
	more-itertools>=9.0,<11.0

[options.extras_require]
postgresql =
	psycopg2~=2.9
hive =
	pyhive[hive,presto,sqlalchemy]~=0.7
presto =
	pyhive[hive,presto,sqlalchemy]~=0.7
snowflake =
	snowflake-sqlalchemy~=1.5
spark =
	pyspark>3.0
	lxml!=5.1.0,>4.8
	ordered-set~=4.1
pyarrow =
	cython~=0.29
	pandas>1.0
	pyarrow>10.0
alembic =
	alembic~=1.13
databricks =
	databricks-sql-connector~=2.9.4
all =
	psycopg2~=2.9
	pyhive[hive,presto,sqlalchemy]~=0.7
	snowflake-sqlalchemy~=1.5
	pyspark>3.0
	lxml!=5.1.0,>4.8
	ordered-set~=4.1
	cython~=0.29
	pandas>1.0
	pyarrow>10.0
	alembic~=1.13
	databricks-sql-connector~=2.9.4

[options.package_data]
* = py.typed

[options.entry_points]
console_scripts =
	analytics-orm = analytics_orm.__main__:main
