name: deploy
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - pyproject.toml
    - setup.py
    - setup.cfg
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - name: Setup
      run: make ci-install
    - name: Distribute package to artifactory
      run: make distribute
    - name: Ensure requirements are up to date
      run: make requirements
    - name: Deploy to DEV + QA
      run: venv/bin/daves-dev-tools airflow deploy dev qa
    - name: Run in QA
      run: venv/bin/daves-dev-tools airflow run -r us-west-2 qa
    - name: Deploy to PROD
      run: venv/bin/daves-dev-tools airflow deploy prod
    - name: Run in PROD
      run: venv/bin/daves-dev-tools airflow run -r us-west-2 prod