name: test
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
    - 'of**'
    paths:
      - setup.py
      - setup.cfg
      - pyproject.toml
      - analytics_orm/**
      - tests/**
      - requirements.txt
      - tox.ini
      - .github/**
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "requirements.txt"
      - run: |
          sudo apt-get update
          sudo apt-get install libpq-dev libsasl2-dev -y
      - run: make ci-install
      - run: make test
