[metadata]
name = airtable-client
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description = A client for the Airtable API
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/data-engineering-ecosystem/sample-client-sdks/open-api-clients/when-openapi-spec-not-provided/airtable-client

[options]
python_requires = ~=3.7
include_package_data = True
packages =
	airtable_client
install_requires =
	sob~=1.50
	cerberus-assistant~=1.0
	oapi

[options.package_data]
* = py.typed
