[tox]
parallel_show_output = False
envlist = black, isort, flake8, mypy, pytest

[testenv]
install_command =
	python3 -m pip install -c requirements.txt {opts} {packages}
extras =
	all
passenv =
	HUDSON_URL
	CI
	LOCALSTACK_HOSTNAME
	SPARK_LOCAL_IP
	AWS_WEB_IDENTITY_TOKEN_FILE
	AWS_ROLE_ARN
	DOCKER_*
setenv =
	PIP_EXTRA_INDEX_URL=NONE
	OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
	AIRFLOW_GPL_UNIDECODE=YES

[testenv:pytest]
deps =
	pytest
	localstack-s3-pyspark
commands_pre =
	analytics-orm spark install-snowflake-jdbc-driver
	localstack-s3-pyspark configure-defaults
commands =
	py.test

[testenv:black]
deps =
	black
commands =
	black --check .

[testenv:isort]
deps =
	isort
commands =
	isort -c .

[testenv:flake8]
deps =
	flake8
commands =
	flake8 --extend-ignore=E501 sample_etl/_business_logic/transform.py

[testenv:mypy]
deps =
	mypy
	types-protobuf!=4.24.0.20240106
commands =
	mypy --install-types --non-interactive
	mypy
