from typing import Dict, FrozenSet, Iterable

from analytics_orm import view
from analytics_orm.declarative import get_class_mapper
from analytics_orm.types import Object
from sqlalchemy.orm import Mapper  # type: ignore
from sqlalchemy.sql.expression import literal  # type: ignore
from sqlalchemy.sql.expression import select  # type: ignore
from sqlalchemy.sql.functions import func  # type: ignore
from sqlalchemy.sql.schema import Column, Table  # type: ignore
from sqlalchemy.sql.selectable import Select  # type: ignore
from sqlalchemy.sql.sqltypes import Integer, String  # type: ignore

from .base import Base

SCHEMA: str = "PUBLIC"

_PRODUCT_SUSTAINABILITY_API_ENUMERATED_VALUE_COLUMNS: FrozenSet[str] = (
    frozenset(
        {
            "DEV_TEAM",
            "SSYY",
            "FACTORY",
            "FIT",
            "MARKETING_TYPE",
            "CLASSIFICATION",
            "SEASON",
            "SILHOUETTE",
            "GENDER",
            "CATEGORY",
            "DIVISION",
            "SEASON_YEAR",
            "AGE",
        }
    )
)


class AlembicVersion(Base):
    """
    `ALEMBIC_VERSION`

    This table stores a database version string generated by the `alembic`
    python package, and is used to determine when/if schema migrations are
    necessary.

    Primary Key:

    - **version_num** (str)
    """

    # This must be lowercase in order to work with alembic
    version_num = Column("version_num", String, primary_key=True)


class BuildOfMaterialSeasonYear(Base):
    """
    BUILD_OF_MATERIAL_SEASON_YEAR

    Properties:

    - build_of_material_id (str)
    - season_year_code (str): 4-digit season + year identifier
    - product_code (str)
    - age_group (str)
    - category (str)
    - classification (str)
    - colorway (str)
    - development_team (str)
    - division (str)
    - factory (str)
    - fit (str)
    - gender (str)
    - marketing_type (str)
    - season (str)
    - year (int)
    - silhouette (str)
    - style_name (str)
    - style_number (str)
    - data (dict): JSON response data
    """

    build_of_material_id = Column(
        "BUILD_OF_MATERIAL_ID",
        String(36),
        primary_key=True,
        autoincrement=False,
        comment="Build of Material Identifier",
        index=True,
    )
    season_year_code = Column(
        "SEASON_YEAR_CODE",
        String(4),
        primary_key=True,
        comment="Season/Year Code",
        index=True,
    )
    product_code = Column(
        "PRODUCT_CODE",
        String(64),
        comment="{Style}-{Colorway}",
        index=True,
    )
    age_group = Column(
        "AGE_GROUP",
        String(12),
        index=True,
    )
    category = Column(
        "CATEGORY",
        String(25),
        comment="MMX Category",
        index=True,
    )
    classification = Column(
        "CLASSIFICATION",
        String(17),
        index=True,
    )
    colorway = Column(
        "COLORWAY",
        String(3),
        nullable=True,
        index=True,
    )
    development_team = Column(
        "DEVELOPMENT_TEAM",
        String(32),
        index=True,
    )
    division = Column(
        "DIVISION",
        String(19),
        index=True,
    )
    factory = Column(
        "FACTORY",
        String(5),
        index=True,
    )
    fit = Column(
        "FIT",
        String(12),
        index=True,
    )
    gender = Column(
        "GENDER",
        String(6),
        index=True,
    )
    marketing_type = Column(
        "MARKETING_TYPE",
        String(23),
        index=True,
    )
    season = Column(
        "SEASON",
        String(2),
        index=True,
    )
    year = Column(
        "YEAR",
        Integer,
        index=True,
    )
    silhouette = Column(
        "SILHOUETTE",
        String(64),
        index=True,
    )
    style_name = Column(
        "STYLE_NAME",
        String(30),
        index=True,
    )
    style_number = Column(
        "STYLE_NUMBER",
        String(25),
        nullable=True,
        index=True,
    )
    data = Column(
        "DATA",
        Object,
        autoincrement=False,
        comment="JSON Data for API consumption",
    )


def _select_product_sustainability_api_v() -> Select:
    """
    This function generates the `SELECT` statement for the view
    `PUBLIC.PRODUCT_SUSTAINABILITY_API_V`.
    """
    mapper: Mapper = get_class_mapper(BuildOfMaterialSeasonYear)
    column: Column
    return select(
        *(
            (
                column.label(
                    _translate_product_sustainability_api_column_name(
                        column.name
                    )
                )
            )
            for column in mapper.columns.values()
        )
    )


def _translate_product_sustainability_api_column_name(
    column_name: str,
) -> str:
    translated_name: str
    if column_name.upper() == "BUILD_OF_MATERIAL_ID":
        translated_name = "BOM_ID"
    elif column_name.upper() == "SEASON_YEAR_CODE":
        translated_name = "SSYY"
    elif column_name.upper() == "DEVELOPMENT_TEAM":
        translated_name = "DEV_TEAM"
    elif column_name.upper() == "YEAR":
        translated_name = "SEASON_YEAR"
    elif column_name.upper() == "AGE_GROUP":
        translated_name = "AGE"
    else:
        translated_name = column_name.upper()
    return translated_name


@view.create_as(_select_product_sustainability_api_v())
class ProductSustainabilityApiV(Base):
    """
    PRODUCT_SUSTAINABILITY_API_V

    This view is for consumption by the Product Sustainability API only.

    Properties:

    - bom_id (str): Build-of-material ID
    - ssyy (str): 4-digit season + year code
    - product_code (str)
    - age (str)
    - category (str)
    - classification (str)
    - colorway (str)
    - dev_team (str)
    - division (str)
    - factory (str)
    - fit (str)
    - gender (str)
    - marketing_type (str)
    - season (str)
    - season_year (int)
    - silhouette (str)
    - style_name (str)
    - style_number (str)
    - data (dict): JSON response data
    """

    bom_id = Column(
        "BOM_ID",
        String,
        primary_key=True,
        autoincrement=False,
        # comment="Build of Material Identifier",
    )
    ssyy = Column(
        "SSYY",
        String,
        primary_key=True,
        # comment="Season/Year Code",
    )
    product_code = Column(
        "PRODUCT_CODE",
        String,
        # comment="{Style}-{Colorway}",
    )
    age = Column("AGE", String, nullable=True)
    category = Column(
        "CATEGORY",
        String,
        # comment="MMX Category",
    )
    classification = Column("CLASSIFICATION", String)
    colorway = Column("COLORWAY", String)
    dev_team = Column("DEV_TEAM", String)
    division = Column("DIVISION", String)
    factory = Column("FACTORY", String)
    fit = Column("FIT", String)
    gender = Column("GENDER", String)
    marketing_type = Column("MARKETING_TYPE", String)
    season = Column("SEASON", String)
    season_year = Column("SEASON_YEAR", Integer)
    silhouette = Column("SILHOUETTE", String)
    style_name = Column("STYLE_NAME", String)
    style_number = Column("STYLE_NUMBER", String)
    data = Column(
        "DATA",
        Object,
        nullable=False,
        autoincrement=False,
        # comment="API Response Data in JSON format for a BOM + Season/Year",
    )


def _iter_build_of_material_season_year_search_column_names() -> Iterable[str]:
    column: Column
    column_name: str
    return filter(
        lambda column_name: column_name != "DATA",
        map(
            lambda column: column.name,
            get_class_mapper(BuildOfMaterialSeasonYear).columns.values(),
        ),
    )


def _select_product_sustainability_api_dimensions_mv() -> Select:
    """
    This function generates the `SELECT` statement for the materialized view
    `PUBLIC.PRODUCT_SUSTAINABILITY_API_DIMENSIONS_MV`.
    """
    build_of_material_season_year_table: Table = (
        BuildOfMaterialSeasonYear.__table__
    )
    return select(
        *(
            (
                func.json_agg(
                    build_of_material_season_year_table.columns[
                        column_name
                    ].distinct()
                ).label(
                    _translate_product_sustainability_api_column_name(
                        column_name
                    )
                )
                if (
                    _translate_product_sustainability_api_column_name(
                        column_name
                    )
                    in _PRODUCT_SUSTAINABILITY_API_ENUMERATED_VALUE_COLUMNS
                )
                else literal("FUZZY").label(
                    _translate_product_sustainability_api_column_name(
                        column_name
                    )
                )
            )
            for column_name in (
                _iter_build_of_material_season_year_search_column_names()
            )
        )
    )


@view.create_as(
    statement=_select_product_sustainability_api_dimensions_mv(),
    materialized=True,
)
class ProductSustainabilityApiDimensionsMv(Base):
    """
    PRODUCT_SUSTAINABILITY_API_DIMENSIONS_MV

    This materialized view is for consumption by the Product Sustainability
    API only.

    Primary Key:

    - bom_id (str)

    Properties:

    - ssyy (dict): JSON data
    - product_code (str)
    - colorway (str)
    - factory (str)
    - style_name (str)
    - style_number (str)
    - age (dict): JSON data
    - category (dict): JSON data
    - classification (dict): JSON data
    - dev_team (dict): JSON data
    - division (dict): JSON data
    - dev_team (dict): JSON data
    - fit (dict): JSON data
    - fit (dict): JSON data
    - marketing_type (dict): JSON data
    - season (dict): JSON data
    - season_year (dict): JSON data
    - silhouette (dict): JSON data
    """

    __table_args__: Dict[str, str] = dict(sqlite_table_name="")

    bom_id = Column("BOM_ID", String, primary_key=True)
    ssyy = Column(
        "SSYY",
        Object,
        nullable=False,
        # comment="drop down options for Season/Year Code",
    )
    product_code = Column("PRODUCT_CODE", String)
    age = Column(
        "AGE",
        Object,
        nullable=False,
        # comment="drop down options for age",
    )
    category = Column(
        "CATEGORY",
        Object,
        nullable=False,
        # comment="drop down options for category",
    )
    classification = Column(
        "CLASSIFICATION",
        Object,
        nullable=False,
        # comment="drop down options for classification",
    )
    colorway = Column("COLORWAY", String)
    dev_team = Column(
        "DEV_TEAM",
        Object,
        nullable=False,
        # comment="drop down options for dev_team",
    )
    division = Column(
        "DIVISION",
        Object,
        nullable=False,
        # comment="drop down options for division",
    )
    factory = Column("FACTORY", Object, nullable=False)
    fit = Column(
        "FIT",
        Object,
        nullable=False,
        # comment="drop down options for fit",
    )
    gender = Column(
        "GENDER",
        Object,
        nullable=False,
        # comment="drop down options for gender",
    )
    marketing_type = Column(
        "MARKETING_TYPE",
        Object,
        nullable=False,
        # comment="drop down options for marketing_type",
    )
    season = Column(
        "SEASON",
        Object,
        nullable=False,
        # comment="drop down options for season",
    )
    season_year = Column(
        "SEASON_YEAR",
        Object,
        nullable=False,
        # comment="drop down options for season_year",
    )
    silhouette = Column(
        "SILHOUETTE",
        Object,
        nullable=False,
        # comment="drop down options for silhouette",
    )
    style_name = Column("STYLE_NAME", String)
    style_number = Column("STYLE_NUMBER", String)


class SuppliedMaterial(Base):
    """
    SUPPLIED_MATERIAL

    This table represents a material sourced from a specific supplier.

    Primary Key:

    - supplied_material_id (int)

    Other Columns/Properties:

    - material_id (int) -> Material.material_id
    - footprint (json) = None
    """

    supplied_material_id = Column(
        "SUPPLIED_MATERIAL_ID",
        Integer,
        primary_key=True,
        autoincrement=False,
    )
    footprint = Column("FOOTPRINT", Object)
