from sqlalchemy.sql.expression import literal  # type: ignore
from sqlalchemy.sql.schema import (  # type: ignore # noqa
    Column,
    ForeignKey,
    ForeignKeyConstraint,
)
from sqlalchemy.types import Integer, String  # type: ignore

from .base import Base

SCHEMA: str = __name__.split(".")[-1].upper()


class AlembicVersion(Base):
    """
    ALEMBIC_VERSION

    This table stores a database version string generated by the `alembic`
    python package, and is used to determine when/if schema migrations are
    necessary.

    Primary Key:

    - version_num (str)
    """

    version_num = Column("VERSION_NUM", String, primary_key=True)


class Calculator(Base):
    """
    CALCULATOR

    This table stores calculator version

    Primary Key:

    - calculator_version (str)

    Other columns/properties:

    - ordinal (int)
    - current (int) = 0
    """

    calculator_version = Column(
        "CALCULATOR_VERSION",
        String,
        primary_key=True,
        nullable=False,
    )
    ordinal = Column(
        "ORDINAL",
        Integer,
        nullable=False,
    )
    current = Column(
        "CURRENT",
        Integer,
        default=0,
        server_default=literal(0),
        nullable=False,
    )
