from sqlalchemy.sql.schema import (  # type: ignore # noqa
    Column,
    ForeignKey,
    ForeignKeyConstraint,
)
from sqlalchemy.types import String  # type: ignore

from .base import Base

SCHEMA: str = __name__.split(".")[-1].upper()


class AlembicVersion(Base):
    """
    ALEMBIC_VERSION

    This table stores a database version string generated by the `alembic`
    python package, and is used to determine when/if schema migrations are
    necessary.

    Primary Key:

    - version_num (str)
    """

    version_num = Column("VERSION_NUM", String, primary_key=True)
