[metadata]
name = analytics-etl
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = This is a framework to build ETLs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/analytics-etl

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	analytics_etl
install_requires =
	file-system-client[s3]
	analytics-orm[pyarrow]

[options.extras_require]
spark =
	analytics-orm[databricks,spark]
	delta-spark~=3.1
	databricks-sdk~=0.24
snowflake =
	analytics-orm[snowflake]
databricks =
	nike-analytics-orm[databricks]
postgresql =
	analytics-orm[postgresql]
all =
	analytics-orm[databricks,spark]
	delta-spark~=3.1
	databricks-sdk~=0.24
	analytics-orm[snowflake]
	analytics-orm[postgresql]

[options.entry_points]
console_scripts =
	analytics-etl = analytics_etl.__main__:main

[options.package_data]
* = py.typed
