name: distribute
on:
  workflow_dispatch:
  push:
    branches:
    - mse
    paths:
    - pyproject.toml
    - setup.py
    - setup.cfg
jobs:
  test:
    uses: ./.github/workflows/test.yml
  distribute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install
    - run: make ci-install
    - run: make requirements
    - name: Distribute Python Package to Artifactory
      run: venv/bin/dev-tools pypi distribute --skip-existing
    - name: Update Libraries - DEV + QA
      run: |
        venv/bin/nike-databricks-jobs update-libraries \
        sample-tabular-etl-dev \
        sample-tabular-etl-qa \
        sample-tabular-etl-incremental-dev \
        sample-tabular-etl-incremental-qa
    - name: Delete Init Scripts - DEV
      run: |
        venv/bin/nike-databricks-jobs update-init-scripts \
        sample-tabular-etl-dev \
        sample-tabular-etl-incremental-dev
    - name: Delete Init Script - QA
      run: |
        venv/bin/nike-databricks-jobs update-init-scripts \
        sample-tabular-etl-qa \
        sample-tabular-etl-incremental-qa
    - name: Deploy to Airflow - DEV + QA
      run: venv/bin/dev-tools airflow deploy dev qa
    - name: Run a full load in QA
      run: venv/bin/dev-tools airflow run qa --include sample_tabular_etl
    - name: Update Libraries - PROD
      run: |
        venv/bin/nike-databricks-jobs update-libraries \
        sample-tabular-etl-prod \
        sample-tabular-etl-incremental-prod
    - name: Delete Init Script - PROD
      run: |
        venv/bin/nike-databricks-jobs update-init-scripts \
        sample-tabular-etl-prod \
        sample-tabular-etl-incremental-prod
    - name: Deploy to Airflow - PROD
      run: venv/bin/dev-tools airflow deploy prod
    - name: Run a full load in PROD
      run: venv/bin/dev-tools airflow run prod --include sample_tabular_etl --detach
