[metadata]
name = my-materialize-snowflake-views
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = "Materialize" Snowflake Views
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/my-materialize-snowflake-views

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	my_materialize_snowflake_views
install_requires =
	my-datastore-etl[snowflake]
	my-datastore-model[snowflake]

[options.entry_points]
console_scripts =
	my-materialize-snowflake-views = my_materialize_snowflake_views.__main__:main

[options.package_data]
* = py.typed
my_materialize_snowflake_views = _select_statements/*.sql
