[metadata]
name = python-pacakge-template
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = A cookiecutter template to develop python tools
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddarthm/python-pacakge-template
