[metadata]
name = etl-framework
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/etl-framework

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	etl_framework
install_requires =
	file-system-client[s3]~=1.5
	orm-framework[pyarrow]~=4.1

[options.extras_require]
spark =
	orm-framework[pyspark]~=4.1
snowflake =
	orm-framework[snowflake]~=4.1
postgresql =
	orm-framework[postgresql]~=4.1
all =
	orm-framework[pyspark]~=4.1
	orm-framework[snowflake]~=4.1
	orm-framework[postgresql]~=4.1

[options.entry_points]
console_scripts =
	etl-framework = etl_framework.__main__:main

[options.package_data]
* = py.typed
