[metadata]
name = my-datastore-orm
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = ORM Classes for tables in my datastore
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/my-datastore-orm

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	my_datastore_orm
    my_datastore_orm.dialects
; install_requires =
;     analytics-orm
; [options.extras_require]
; snowflake =
; 	analytics-orm[snowflake]
; pyspark =
; 	analytics-orm[pyspark]
; pyarrow =
; 	analytics-orm[pyarrow]
; all =
; 	analytics-orm[snowflake]
; 	analytics-orm[pyspark]
; 	analytics-orm[pyarrow]

[options.entry_points]
console_scripts =
	my-datastore-orm = my_datastore_orm.__main__:main

[options.package_data]
my_datastore_orm =
	_snowflake_views/*.sql
* = py.typed
