[metadata]
name = my-datastore-orm
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/my-datastore-orm

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	my-datastore-orm
    my-datastore-orm.dialects
install_requires =
    orm-framework
[options.extras_require]
snowflake =
	orm-framework[snowflake]
pyspark =
	orm-framework[pyspark]
pyarrow =
	orm-framework[pyarrow]
all =
	orm-framework[snowflake]
	orm-framework[pyspark]
	orm-framework[pyarrow]

[options.entry_points]
console_scripts =
	my-datastore-orm = my_datastore_orm.__main__:main

[options.package_data]
my_datastore_orm =
	_snowflake_views/*.sql
* = py.typed
