[metadata]
name = data-quality-framework
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-quality-framework

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	data_quality_framework
install_requires =
	file-system-client[s3]
	my-datastore-orm[snowflake]
	my-datastore-etl-wrapper[snowflake]

[options.entry_points]
console_scripts =
	data-quality-framework = data_quality_framework.__main__:main

[options.package_data]
* = py.typed
