[metadata]
name = nike-enablon-client
version = 2.12.0
author_email = lst-sustainability.engineering@nike.com
description = Client for Nike Enablon "Blink" OData API
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/nike-sustainability/nike-enablon-client

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	nike.enablon_client
install_requires =
	sob~=1.50
	oapi~=1.62
	nike-cerberus-assistant~=1.0

[options.package_data]
* = py.typed
