SELECT SEASON_YEAR_CD AS SEASON_YEAR_CODE,
    YEAR_NBR AS YEAR,
    SEASON_CD AS SEASON_CODE,
    FISCAL_YEAR_NBR AS FISCAL_YEAR,
    FISCAL_QUARTER_NBR AS FISCAL_QUARTER,
    CONCAT(
        SUBSTR(CAST(SEASON_YEAR_CD AS VARCHAR(6)), 1, 2),
        SUBSTR(CAST(SEASON_YEAR_CD AS VARCHAR(6)), 5, 2)
    ) AS SEASON_YEAR_CODE_ABBREVIATED
FROM CALENDAR_PROD.BCL.ENTERPRISECALENDAR_V
WHERE DAY_OF_SEASON_NBR = 1
    AND (
        YEAR > 2018
        OR SEASON_YEAR_CD IN ('FA2018', 'HO2018')
    )
ORDER BY CALENDAR_DT