WITH SEASON_YEAR AS (
    SELECT SEASON_YEAR_CD AS SEASON_YEAR_CODE,
        SEASON_NBR AS SEASON_NUMBER,
        YEAR_NBR AS YEAR_NUMBER,
        MIN(CALENDAR_DT) AS SEASON_YEAR_START
    FROM CALENDAR_PROD.BCL.ENTERPRISECALENDAR_V
    GROUP BY SEASON_YEAR_CD,
        SEASON_NBR,
        YEAR_NBR
),
IS_BILL_OF_MATERIAL_COMPLETE AS (
    SELECT PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID AS BILL_OF_MATERIAL_UUID,
        TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE) AS CYCLE_YEAR,
        SUBSTR(TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE), 1, 2) || '20' || SUBSTR(TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE), 3, 2) AS SEASON_YEAR_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.STYLE_NUMBER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLORWAY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LEGACY_FACTORY_CODE,
        (
            CASE
                WHEN SUM(
                    CASE
                        WHEN PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION = 'APPAREL DIVISION' THEN CASE
                            WHEN PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLOR = '{}'
                            AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLOR_PLACEHOLDER_DESCRIPTION IS NULL
                            AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COMPONENT_LINE_ITEM_LIST = '[]' THEN 0
                            ELSE 1
                        END
                        ELSE 1
                    END
                ) = 0 THEN FALSE
                ELSE TRUE
            END
        ) AS IS_COMPLETE
    FROM EDA_PRODUCT_PROD.BCL_GOODS_DEVELOPMENT.PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V,
        TABLE(
            FLATTEN(
                PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CYCLE_YEAR
            )
        ) AS FLATTENED_CYCLE_YEAR
    WHERE (
            SUBSTR(TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE), 3, 2) > 18
            OR TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE) IN ('FA18', 'HO18')
        )
        AND BILL_OF_MATERIAL_STATUS_INDICATOR = TRUE
    GROUP BY PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID,
        FLATTENED_CYCLE_YEAR.VALUE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLORWAY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LEGACY_FACTORY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.STYLE_NUMBER
),
IS_BILL_OF_MATERIAL_COMPLETE_SEASON_YEAR AS (
    SELECT IS_BILL_OF_MATERIAL_COMPLETE.BILL_OF_MATERIAL_UUID,
        IS_BILL_OF_MATERIAL_COMPLETE.CYCLE_YEAR,
        IS_BILL_OF_MATERIAL_COMPLETE.SEASON_YEAR_CODE,
        IS_BILL_OF_MATERIAL_COMPLETE.STYLE_NUMBER,
        IS_BILL_OF_MATERIAL_COMPLETE.COLORWAY_CODE,
        IS_BILL_OF_MATERIAL_COMPLETE.LEGACY_FACTORY_CODE,
        IS_BILL_OF_MATERIAL_COMPLETE.IS_COMPLETE,
        SEASON_YEAR.SEASON_YEAR_START
    FROM IS_BILL_OF_MATERIAL_COMPLETE
        JOIN SEASON_YEAR ON IS_BILL_OF_MATERIAL_COMPLETE.SEASON_YEAR_CODE = SEASON_YEAR.SEASON_YEAR_CODE
),
CANDIDATE_SUBSTITUTE_BILL_OF_MATERIAL AS (
    SELECT INCOMPLETE_BILL_OF_MATERIAL.BILL_OF_MATERIAL_UUID AS INCOMPLETE_BILL_OF_MATERIAL_UUID,
        INCOMPLETE_BILL_OF_MATERIAL.SEASON_YEAR_CODE AS INCOMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        INCOMPLETE_BILL_OF_MATERIAL.CYCLE_YEAR AS INCOMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR,
        COMPLETE_BILL_OF_MATERIAL.BILL_OF_MATERIAL_UUID AS COMPLETE_BILL_OF_MATERIAL_UUID,
        COMPLETE_BILL_OF_MATERIAL.SEASON_YEAR_CODE AS COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        COMPLETE_BILL_OF_MATERIAL.CYCLE_YEAR AS COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR,
        COMPLETE_BILL_OF_MATERIAL.SEASON_YEAR_START AS COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_START
    FROM IS_BILL_OF_MATERIAL_COMPLETE_SEASON_YEAR AS INCOMPLETE_BILL_OF_MATERIAL
        LEFT OUTER JOIN IS_BILL_OF_MATERIAL_COMPLETE_SEASON_YEAR AS COMPLETE_BILL_OF_MATERIAL ON INCOMPLETE_BILL_OF_MATERIAL.STYLE_NUMBER = COMPLETE_BILL_OF_MATERIAL.STYLE_NUMBER
        AND INCOMPLETE_BILL_OF_MATERIAL.COLORWAY_CODE = COMPLETE_BILL_OF_MATERIAL.COLORWAY_CODE
        AND INCOMPLETE_BILL_OF_MATERIAL.LEGACY_FACTORY_CODE = COMPLETE_BILL_OF_MATERIAL.LEGACY_FACTORY_CODE
        AND INCOMPLETE_BILL_OF_MATERIAL.SEASON_YEAR_START > COMPLETE_BILL_OF_MATERIAL.SEASON_YEAR_START
        AND COMPLETE_BILL_OF_MATERIAL.IS_COMPLETE = TRUE
    WHERE INCOMPLETE_BILL_OF_MATERIAL.IS_COMPLETE = FALSE
),
SUBSTITUTE_BILL_OF_MATERIAL AS (
    SELECT INCOMPLETE_BILL_OF_MATERIAL_UUID,
        INCOMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        INCOMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR,
        COMPLETE_BILL_OF_MATERIAL_UUID AS LATEST_COMPLETE_BILL_OF_MATERIAL_UUID,
        COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE AS LATEST_COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR AS LATEST_COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR
    FROM CANDIDATE_SUBSTITUTE_BILL_OF_MATERIAL QUALIFY COMPLETE_BILL_OF_MATERIAL_UUID IS NULL
        OR ROW_NUMBER() OVER (
            PARTITION BY INCOMPLETE_BILL_OF_MATERIAL_UUID,
            INCOMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE
            ORDER BY COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_START DESC
        ) = 1
),
BILL_OF_MATERIAL_HEADER AS (
    SELECT PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION
        ) AS DIVISION,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_IDENTIFIER
        ) AS BOM_IDENTIFIER,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_COLORWAY_IDENTIFIER
        ) AS DEVELOPMENT_COLORWAY_IDENTIFIER,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_V.PRODUCT_UUID
        ) AS PRODUCT_UUID,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLORWAY_CODE
        ) AS COLORWAY_CODE,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.STYLE_NUMBER
        ) AS STYLE,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LEGACY_FACTORY_CODE
        ) AS FCTY,
        ANY_VALUE(
            PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CYCLE_YEAR
        ) AS CYCLE_YEAR
    FROM EDA_PRODUCT_PROD.BCL_GOODS_DEVELOPMENT.PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V
        LEFT JOIN EDA_PRODUCT_PROD.BCL_GOODS_DEVELOPMENT.PRODUCT_DEVELOPMENT_BOM_V ON PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID = PRODUCT_DEVELOPMENT_BOM_V.PRODUCT_DEVELOPMENT_BOM_UUID
        AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CYCLE_YEAR = PRODUCT_DEVELOPMENT_BOM_V.CYCLE_YEAR
    WHERE PRODUCT_DEVELOPMENT_BOM_V.BILL_OF_MATERIAL_STATUS_INDICATOR = TRUE
        AND (
            (PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION = 'FOOTWEAR DIVISION' AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.IS_BOM_CONVERTED_INDICATOR = FALSE)
            OR (PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION = 'EQUIPMENT DIVISION' AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.IS_BOM_CONVERTED_INDICATOR = FALSE)
            OR (PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION = 'APPAREL DIVISION' AND PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.IS_BOM_CONVERTED_INDICATOR IS NULL)
            )
    GROUP BY PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID
),
FLATTENED_BILL_OF_MATERIAL_HEADER AS (
    SELECT PRODUCT_DEVELOPMENT_BOM_UUID,
        DEVELOPMENT_COLORWAY_IDENTIFIER,
        COLORWAY_CODE AS BILL_OF_MATERIAL_COLORWAY_CODE,
        BOM_IDENTIFIER,
        PRODUCT_UUID,
        DIVISION,
        STYLE,
        FCTY,
        TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE) AS CYCLE_YEAR
    FROM BILL_OF_MATERIAL_HEADER,
        TABLE(FLATTEN(BILL_OF_MATERIAL_HEADER.CYCLE_YEAR)) AS FLATTENED_CYCLE_YEAR
),
UNIFIED_BILL_OF_MATERIAL AS (
    SELECT FLATTENED_BILL_OF_MATERIAL_HEADER.PRODUCT_DEVELOPMENT_BOM_UUID,
        FLATTENED_BILL_OF_MATERIAL_HEADER.BOM_IDENTIFIER,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.DEVELOPMENT_COLORWAY_IDENTIFIER,
            FLATTENED_BILL_OF_MATERIAL_HEADER.DEVELOPMENT_COLORWAY_IDENTIFIER
        ) AS COLORWAY_IDENTIFIER,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.PRODUCT_UUID,
            FLATTENED_BILL_OF_MATERIAL_HEADER.PRODUCT_UUID
        ) AS PRODUCT_UUID,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.STYLE,
            FLATTENED_BILL_OF_MATERIAL_HEADER.STYLE
        ) || '-' || COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.BILL_OF_MATERIAL_COLORWAY_CODE,
            FLATTENED_BILL_OF_MATERIAL_HEADER.BILL_OF_MATERIAL_COLORWAY_CODE,
            PRODUCT_COLORWAY_CODE
        ) AS PRODUCT_CODE,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.BILL_OF_MATERIAL_COLORWAY_CODE,
            FLATTENED_BILL_OF_MATERIAL_HEADER.BILL_OF_MATERIAL_COLORWAY_CODE,
            PRODUCT_COLORWAY_CODE
        ) AS COLORWAY,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.STYLE,
            FLATTENED_BILL_OF_MATERIAL_HEADER.STYLE
        ) AS STYLE,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.DIVISION,
            FLATTENED_BILL_OF_MATERIAL_HEADER.DIVISION
        ) AS DIVISION,
        COALESCE(
            SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.FCTY,
            FLATTENED_BILL_OF_MATERIAL_HEADER.FCTY
        ) AS FCTY,
        FLATTENED_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR,
        'UNIFIED BOM' AS BILL_OF_MATERIAL_SOURCE,
        SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_UUID,
        SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR
    FROM FLATTENED_BILL_OF_MATERIAL_HEADER
        LEFT JOIN PES_ARIA_PRODUCT_PROD.PROCESSED.PCX_DEV_CLRWY_V COLOR ON COLOR.DEV_CLRWY_ID = FLATTENED_BILL_OF_MATERIAL_HEADER.DEVELOPMENT_COLORWAY_IDENTIFIER
        LEFT JOIN EDA_PRODUCT_PROD.BCL_PRODUCT_LIBRARY.PRODUCT_V PRODUCT ON COLOR.PROD_ID = PRODUCT.PRODUCT_IDENTIFIER
        LEFT OUTER JOIN SUBSTITUTE_BILL_OF_MATERIAL ON FLATTENED_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR = SUBSTITUTE_BILL_OF_MATERIAL.INCOMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR
        AND FLATTENED_BILL_OF_MATERIAL_HEADER.PRODUCT_DEVELOPMENT_BOM_UUID = SUBSTITUTE_BILL_OF_MATERIAL.INCOMPLETE_BILL_OF_MATERIAL_UUID
        LEFT OUTER JOIN FLATTENED_BILL_OF_MATERIAL_HEADER AS SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER ON SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR = SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR
        AND SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_UUID = SUBSTITUTE_FLATTENED_BILL_OF_MATERIAL_HEADER.PRODUCT_DEVELOPMENT_BOM_UUID
    WHERE (
            RIGHT(FLATTENED_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR, 2) > '18'
            OR FLATTENED_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR IN ('FA18', 'HO18')
        )
        AND (
            -- Don't include incomplete BOMs for which we have no substitute
            SUBSTITUTE_BILL_OF_MATERIAL.INCOMPLETE_BILL_OF_MATERIAL_UUID IS NULL
            OR SUBSTITUTE_BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_UUID IS NOT NULL
        )
),
SPENDCUBE_BOMS AS (
    SELECT RANK() OVER (
            PARTITION BY PROD_CD,
            SEASON_CODE,
            SEASON_YEAR,
            FCTY_CD
            ORDER BY CBD_ID DESC
        ) AS CBD_RANK,
        PCX_MATL_ID,
        PROD_CD,
        MATERIAL_NUM,
        SPLR_MATL_NUM,
        SEASON_CODE,
        SEASON_YEAR,
        SUPPLIER_NUM,
        USAGE_UOM,
        PCC_NET_KG,
        PCC_GROSS_KG,
        CBD_SCTN,
        CMPNT_NM,
        FCTY_CD,
        DEFECTIVE_LOSS_PERC,
        GROSS,
        EFFICIENCY_PERC,
        GROSS * (EFFICIENCY_PERC) AS NET,
        GROSS * (1 - EFFICIENCY_PERC) AS WASTE,
        ROW_NUMBER() OVER (
            PARTITION BY PROD_CD,
            SEASON_CODE,
            SEASON_YEAR,
            FCTY_CD
            ORDER BY SPLR_MATL_NUM,
                CMPNT_NM
        ) AS LINE_ITEM_NUMBER
    FROM "PES_ARIA_PRODUCT_PROD"."PROCESSED"."SPENDCUBE_V"
    WHERE CBD_SCTN IN (
            'UPPER',
            'MIDSOLE',
            'OUTSOLE',
            'AIR'
        )
        AND CBD_CLAS = 'MTL'
        AND MATL_TYPE <> 'LABOR, OVERHEAD, PROCESSING'
        AND (
            SEASON_YEAR > '2018'
            OR (
                SEASON_CODE IN ('FA', 'HO')
                AND SEASON_YEAR = '2018'
            )
        )
),
SPENDCUBE_BILL_OF_MATERIAL_HEADER AS (
    SELECT PROD_CD || '_' || SEASON_CODE || SUBSTR(SEASON_YEAR, 3, 2) || '_' || FCTY_CD AS PRODUCT_DEVELOPMENT_BOM_UUID,
        NULL AS BOM_IDENTIFIER,
        NULL AS COLORWAY_IDENTIFIER,
        ANY_VALUE(GLOBAL_PRODUCT_LINE_V1.PRODUCT_UUID) AS PRODUCT_UUID,
        PROD_CD AS PRODUCT_CODE,
        SUBSTR(PROD_CD, 8, 3) AS COLORWAY,
        SUBSTR(PROD_CD, 1, 6) AS STYLE,
        'FOOTWEAR DIVISION' AS DIVISION,
        FCTY_CD AS FCTY,
        SEASON_CODE || SUBSTR(SEASON_YEAR, 3, 2) AS CYCLE_YEAR,
        'SPENDCUBE' AS BILL_OF_MATERIAL_SOURCE,
        NULL AS LATEST_COMPLETE_BILL_OF_MATERIAL_UUID,
        NULL AS LATEST_COMPLETE_BILL_OF_MATERIAL_SEASON_YEAR_CODE,
        NULL AS LATEST_COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR
    FROM SPENDCUBE_BOMS
        LEFT JOIN EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1 ON SPENDCUBE_BOMS.PROD_CD = GLOBAL_PRODUCT_LINE_V1.PRODUCT_CODE
    WHERE CBD_RANK = 1
    GROUP BY PROD_CD,
        SEASON_CODE,
        SEASON_YEAR,
        FCTY_CD
),
BILL_OF_MATERIAL AS (
    SELECT *
    FROM UNIFIED_BILL_OF_MATERIAL
    UNION
    SELECT SPENDCUBE_BILL_OF_MATERIAL_HEADER.*
    FROM SPENDCUBE_BILL_OF_MATERIAL_HEADER
        LEFT JOIN UNIFIED_BILL_OF_MATERIAL ON SPENDCUBE_BILL_OF_MATERIAL_HEADER.PRODUCT_CODE = UNIFIED_BILL_OF_MATERIAL.PRODUCT_CODE
        AND SPENDCUBE_BILL_OF_MATERIAL_HEADER.CYCLE_YEAR = UNIFIED_BILL_OF_MATERIAL.CYCLE_YEAR
        AND SPENDCUBE_BILL_OF_MATERIAL_HEADER.FCTY = UNIFIED_BILL_OF_MATERIAL.FCTY
    WHERE UNIFIED_BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID IS NULL
),
DP_AGG AS (
    SELECT SUBSTR(PLANNING_PRODUCT_CD, 1, 6) AS STYLE,
        SUBSTR(PLANNING_PRODUCT_CD, 8, 3) AS COLORWAY,
        SUBSTR(BUSINESS_SEASON_CD, 5, 2) || SUBSTR(BUSINESS_SEASON_CD, 3, 2) AS CYCLE_YEAR,
        SUM(DEMAND_PLAN_QTY_3_0) AS DP_VOLUME
    FROM DA_DSM_SCANALYTICS_PROD.INTEGRATED.GLBL_DEMAND_PLAN_V
    WHERE MILESTONE_CD = 'Current Forecast'
        AND DIVISION_DESC IN ('APPAREL DIVISION', 'FOOTWEAR DIVISION')
        AND DEMAND_PLAN_QTY_3_0 > 0
        AND HARMONIZED_STYLE_NBR <> '*UNK*'
    GROUP BY SUBSTR(PLANNING_PRODUCT_CD, 1, 6),
        SUBSTR(PLANNING_PRODUCT_CD, 8, 3),
        SUBSTR(BUSINESS_SEASON_CD, 5, 2) || SUBSTR(BUSINESS_SEASON_CD, 3, 2)
),
DP_VOLUME AS (
    SELECT DP_AGG.STYLE,
        DP_AGG.COLORWAY,
        DP_AGG.CYCLE_YEAR,
        ANY_VALUE(DP_AGG.DP_VOLUME) AS DP_VOLUME,
        ARRAY_CAT(
            ARRAY_AGG(DISTINCT EXACT_BOM.PRODUCT_DEVELOPMENT_BOM_UUID),
            ARRAY_AGG(
                DISTINCT INEXACT_BOM.PRODUCT_DEVELOPMENT_BOM_UUID
            )
        ) AS BOM_IDS
    FROM DP_AGG
        LEFT JOIN BILL_OF_MATERIAL AS EXACT_BOM ON EXACT_BOM.COLORWAY = DP_AGG.COLORWAY
        AND EXACT_BOM.STYLE = DP_AGG.STYLE
        AND EXACT_BOM.CYCLE_YEAR = DP_AGG.CYCLE_YEAR
        LEFT JOIN BILL_OF_MATERIAL AS INEXACT_BOM ON INEXACT_BOM.STYLE = DP_AGG.STYLE
        AND INEXACT_BOM.CYCLE_YEAR = DP_AGG.CYCLE_YEAR
        AND EXACT_BOM.PRODUCT_DEVELOPMENT_BOM_UUID IS NULL
    GROUP BY DP_AGG.STYLE,
        DP_AGG.COLORWAY,
        DP_AGG.CYCLE_YEAR
    HAVING ARRAY_SIZE(BOM_IDS) > 0
),
PRODUCT_LINE AS (
    SELECT PRODUCT_UUID,
        MAX(PRODUCT_CODE) AS PRODUCT_CODE,
        MAX(AGE_DESCRIPTION) AS AGE,
        MAX(GENDER_DESCRIPTION) AS GENDER,
        MAX(SILHOUETTE_DESCRIPTION) AS SILHOUETTE,
        MAX(STYLE_NAME) AS STYLE_NAME,
        MAX(MERCHANDISING_CLASSIFICATION_DESCRIPTION) AS CLASSIFICATION,
        MAX(GLOBAL_CATEGORY_CORE_FOCUS_DESCRIPTION) AS CATEGORY,
        MAX(FIT_DESCRIPTION) AS FIT,
        MAX(DEVELOPMENT_TEAM_NAME) AS DEV_TEAM,
        MAX(PRIMARY_MARKETING_TYPE_DESCRIPTION) AS MARKETING_TYPE,
        MAX(SUBSTR(PRODUCT_CODE, 1, 6)) AS STYLE,
        MAX(SUBSTR(PRODUCT_CODE, 8, 3)) AS COLORWAY,
        MAX(DIVISION_DESCRIPTION) AS DIVISION,
        SUBSTR(SEASON_YEAR_DESCRIPTION, 1, 2) || SUBSTR(SEASON_YEAR_DESCRIPTION, 5, 2) AS CYCLE_YEAR,
        MAX(BUSINESS_ORGANIZATION_DESCRIPTION) AS BUSINESS_ORGANIZATION,
        MAX(MODEL_OFFERING_SPONSOR_DESCRIPTION) AS SPONSOR,
        MAX(CONSUMER_PURPOSE_DESCRIPTION) AS CONSUMER_PURPOSE,
        MAX(CONSUMER_FOCUS_DESCRIPTION) AS CONSUMER_FOCUS,
        MAX(TEAM_NAME) AS TEAM_NAME,
        MAX(SUBSTR(PRODUCT_CODE, 1, 6)) AS STYLE_CODE,
        MAX(MODEL_IDENTIFIER) AS MODEL_ID,
        MAX(MODEL_NAME) AS MODEL_NAME,
        MAX(CONSUMER_USE_DESCRIPTION) AS CONSUMER_USE,
        MAX(CONSUMER_GROUP_DESCRIPTION) AS CONSUMER_GROUP,
        MAX(SUB_CATEGORY_DESCRIPTION) AS SUB_CATEGORY,
        MAX(MATERIAL_INTENT_DESCRIPTION) AS MATERIAL_INTENT,
        MAX(CONSTRUCTION_METHOD_DESCRIPTION) AS CONSTRUCTION,
        MAX(PRODUCT_TIER_DESCRIPTION) AS PRODUCT_TIER,
        TRIM(
            SPLIT_PART(
                SPLIT_PART(MAX(MARKETING_INITIATIVES), ':', 2),
                ',',
                0
            ),
            '"'
        ) AS MARKETING_INITIATIVE,
        TRIM(
            SPLIT_PART(
                SPLIT_PART(MAX(MODEL_OFFERING_GROUPS), ':', 2),
                ',',
                0
            ),
            '"'
        ) AS MO_GROUP,
        MAX(LINE_EVOLUTION_DESCRIPTION) AS LINE_EVOLUTION,
        MAX(PRODUCT_CARRYOVER_STATUS_INDICATOR) AS CARRYOVER_STATUS,
        MAX(CATEGORY_PRODUCT_LINE_MANAGER_NAME) AS PLM_NAME,
        MAX(CATEGORY_PRODUCT_LINE_MANAGER_USER_CODE) AS PLM_CODE,
        MAX(CONSUMER_CONSTRUCT_DIMENSION_NAME) AS CONSUMER_CONSTRUCT_DIMENSION_NAME,
        MAX(CONSUMER_CONSTRUCT_GLOBAL_CONSUMER_OFFENSE_NAME) AS CONSUMER_CONSTRUCT_GLOBAL_CONSUMER_OFFENSE_NAME,
        MAX(PRODUCT_PLANNING_AGE_GENDER_NAME) AS PRODUCT_PLANNING_AGE_GENDER_NAME,
        MAX(PRODUCT_PLANNING_DIVISION_NAME) AS PRODUCT_PLANNING_DIVISION_NAME,
        MAX(PRODUCT_PLANNING_INTENDED_USE_NAME) AS PRODUCT_PLANNING_INTENDED_USE_NAME,
        MAX(PRODUCT_PLANNING_SILHOUETTE_NAME) AS PRODUCT_PLANNING_SILHOUETTE_NAME,
        MAX(PRODUCT_PLANNING_STRUCTURE_NAME) AS PRODUCT_PLANNING_STRUCTURE_NAME,
        MAX(PRODUCT_PLANNING_SUB_SILHOUETTE_NAME) AS PRODUCT_PLANNING_SUB_SILHOUETTE_NAME,
        MAX(PRODUCT_OFFERING_STATUS_INDICATOR) AS PRODUCT_OFFERING_STATUS_INDICATOR
    FROM EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1 GLOBAL_PRODUCT_LINE_V1
    WHERE GLOBAL_PRODUCT_LINE_V1.PRODUCT_OFFERING_STATUS_INDICATOR = 'A'
        AND GLOBAL_PRODUCT_LINE_V1.PRODUCT_UUID IS NOT NULL
        AND SEASON_YEAR_DESCRIPTION IS NOT NULL
        AND (
            CAST(SUBSTR(SEASON_YEAR_DESCRIPTION, 3, 4) AS INTEGER) > 2018
            OR SEASON_YEAR_DESCRIPTION IN ('FA2018', 'HO2018')
        )
    GROUP BY PRODUCT_UUID,
        SUBSTR(SEASON_YEAR_DESCRIPTION, 1, 2) || SUBSTR(SEASON_YEAR_DESCRIPTION, 5, 2)
),
COST_BREAKDOWN AS (
    SELECT SESN_SSYY AS CYCLE_YEAR,
        BOM_HDR_ID,
        LGCY_FCTY_CD AS FCTY,
        DEV_CLRWY_ID AS COLORWAY_IDENTIFIER,
        MILESTONE AS MILESTONE,
        TECH_DFCLTY_CD AS TECH_DFCLTY,
        RANK() OVER (
            PARTITION BY SESN_SSYY,
            PROD_CD
            ORDER BY MAX(CST_SHT_CALCN_DT) DESC,
                MAX(CST_SHT_QTE_PCX_CST_SHT_VER_NBR) DESC
        ) AS RANK
    FROM PES_ARIA_PRODUCT_PROD.PROCESSED.PCX_QTE_HIST_RPT_V
    GROUP BY SESN_SSYY,
        PROD_CD,
        LGCY_FCTY_CD,
        DEV_CLRWY_ID,
        TECH_DFCLTY_CD,
        MILESTONE,
        BOM_HDR_ID
),
WEIGHTS AS (
    SELECT CASE
            WHEN MEDIAN(PRODUCT_NET_WEIGHT_KG) > 100 THEN MEDIAN(PRODUCT_NET_WEIGHT_KG) / 1000
            ELSE MEDIAN(PRODUCT_NET_WEIGHT_KG)
        END AS NET,
        CASE
            WHEN MEDIAN(PRODUCT_NET_NET_WEIGHT_KG) > 100 THEN MEDIAN(PRODUCT_NET_NET_WEIGHT_KG) / 1000
            ELSE MEDIAN(PRODUCT_NET_NET_WEIGHT_KG)
        END AS NET_NET,
        SUBSTR(PRODUCT_V.PRODUCT_CODE, 1, 6) AS STYLE
    FROM EDA_PRODUCT_PROD.BCL_PRODUCT_LIBRARY.MASTER_SIZE_V MASTER_SIZE_V
        INNER JOIN EDA_PRODUCT_PROD.BCL_PRODUCT_LIBRARY.PRODUCT_V PRODUCT_V ON PRODUCT_V.PRODUCT_CODE = MASTER_SIZE_V.PRODUCT_CODE
    WHERE LENGTH(
            TRIM(REPLACE(PRODUCT_NET_WEIGHT_KG::Text, '.'), 0)
        ) > 1
    GROUP BY SUBSTR(PRODUCT_V.PRODUCT_CODE, 1, 6)
),
FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V AS (
    SELECT PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_COLORWAY_SOURCE_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_COLORWAY_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LEGACY_FACTORY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.STYLE_NUMBER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLORWAY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SOURCING_CONFIGURATION_IDENTIFIER,
        TO_VARCHAR(FLATTENED_CYCLE_YEAR.VALUE) AS CYCLE_YEAR,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_COLORWAY_SEASON_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SOURCING_CONFIGURATION_COLORWAY_SEASON,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_STYLE_TYPE_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_STYLE_TYPE_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DIVISION_DESCRIPTION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_DESCRIPTION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_COMMENTS,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BILL_OF_MATERIAL_STATE_DESCRIPTION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BILL_OF_MATERIAL_STATUS_INDICATOR,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_HEADER_CREATE_TIMESTAMP,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_HEADER_CHANGE_TIMESTAMP,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_HEADER_CREATED_BY,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_HEADER_MODIFIED_BY,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.NIKE_PRODUCT_DEVELOPER_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_NUMBER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BILL_OF_MATERIALS_SECTION_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BILL_OF_MATERIALS_SECTION_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PARENT_BOM_LINE_ITEM_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.MATERIAL,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIED_MATERIAL,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_INFORMATION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.MATERIAL_ITEM_PLACEHOLDER_DESCRIPTION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIED_MATERIAL_COLOR_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLOR,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.TEAM_PLAYER_GRAPHIC,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIED_MATERIAL_COLOR_IS_MULTIPLE_COLORS,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLOR_PLACEHOLDER_DESCRIPTION,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PART_NAME_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PART_NAME_IDENTIFIERS,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PART_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PATTERN_PART_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PATTERN_PART_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.USAGE_UNIT_OF_MEASURE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LINE_ITEM_QUANTITY,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.NET_USAGE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.WASTE_USAGE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PART_YIELD,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_COMMENTS,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.AUDIT_STRING,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CUSHIONING_TYPE_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.LEGACY_MATERIAL_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIER_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIER_MANUFACTURING_COUNTRY_CODE,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COMPONENT_LINE_ITEM_LIST,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_CREATE_TIMESTAMP,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_CHANGE_TIMESTAMP,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_MODIFIED_BY,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_COLORWAY_STATE_IDENTIFIER,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.DEVELOPMENT_COLORWAY_STATE_NAME,
        PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CHANGE_TIMESTAMP
    FROM EDA_PRODUCT_PROD.BCL_GOODS_DEVELOPMENT.PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V,
        TABLE(
            FLATTEN(
                PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CYCLE_YEAR
            )
        ) AS FLATTENED_CYCLE_YEAR
),
BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL AS (
    SELECT BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID,
        BILL_OF_MATERIAL.CYCLE_YEAR,
        COALESCE(
            FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.SUPPLIED_MATERIAL :id,
            SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
        ) AS SUPPLIED_MATERIAL_ID,
        UPPER(
            COALESCE(
                FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.USAGE_UNIT_OF_MEASURE,
                SPENDCUBE_BOMS.USAGE_UOM
            )
        ) AS USAGE_UNIT_OF_MEASURE,
        COALESCE(
            FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.NET_USAGE,
            SPENDCUBE_BOMS.NET
        ) AS NET_USAGE,
        COALESCE(
            FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.WASTE_USAGE,
            SPENDCUBE_BOMS.WASTE
        ) AS WASTE_USAGE,
        UPPER(
            COALESCE(
                FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BILL_OF_MATERIALS_SECTION_NAME,
                SPENDCUBE_BOMS.CBD_SCTN
            )
        ) AS BILL_OF_MATERIALS_SECTION_NAME,
        COALESCE(
            FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PART_NAME,
            SPENDCUBE_BOMS.CMPNT_NM
        ) AS PART_NAME,
        COALESCE(
            FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.BOM_LINE_ITEM_NUMBER,
            SPENDCUBE_BOMS.LINE_ITEM_NUMBER
        ) AS BOM_LINE_ITEM_NUMBER,
        SPENDCUBE_BOMS.DEFECTIVE_LOSS_PERC AS DEFECTIVE_LOSS_PERCENTAGE,
        FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.MATERIAL_ITEM_PLACEHOLDER_DESCRIPTION AS MATERIAL_ITEM_PLACEHOLDER_DESCRIPTION,
        FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COLOR_PLACEHOLDER_DESCRIPTION AS COLOR_PLACEHOLDER_DESCRIPTION,
        FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.COMPONENT_LINE_ITEM_LIST AS COMPONENT_LINE_ITEM_LIST,
        CASE
            WHEN BILL_OF_MATERIAL.BILL_OF_MATERIAL_SOURCE = 'UNIFIED BOM' AND BILL_OF_MATERIAL.DIVISION = 'FOOTWEAR DIVISION' AND SPENDCUBE_BOMS.PROD_CD IS NOT NULL THEN 'UNIFIED BOM/SPENDCUBE'
            ELSE BILL_OF_MATERIAL.BILL_OF_MATERIAL_SOURCE
        END AS BILL_OF_MATERIAL_SOURCE
    FROM BILL_OF_MATERIAL
        LEFT JOIN SPENDCUBE_BOMS ON BILL_OF_MATERIAL.PRODUCT_CODE = SPENDCUBE_BOMS.PROD_CD
        AND BILL_OF_MATERIAL.FCTY = SPENDCUBE_BOMS.FCTY_CD
        AND BILL_OF_MATERIAL.CYCLE_YEAR = SPENDCUBE_BOMS.SEASON_CODE || SUBSTR(SPENDCUBE_BOMS.SEASON_YEAR, 3, 2)
        AND BILL_OF_MATERIAL.DIVISION = 'FOOTWEAR DIVISION'
        AND CBD_RANK = 1
        LEFT JOIN FND_MATERIAL.SUPPLIED_MATERIAL SUPPLIED_MATERIAL ON SPENDCUBE_BOMS.SPLR_MATL_NUM = SUPPLIED_MATERIAL.LEGACY_CODE
        LEFT JOIN FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V ON COALESCE(
            BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_UUID,
            BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID
        ) = FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.PRODUCT_DEVELOPMENT_BOM_UUID
        AND COALESCE(
            BILL_OF_MATERIAL.LATEST_COMPLETE_BILL_OF_MATERIAL_CYCLE_YEAR,
            BILL_OF_MATERIAL.CYCLE_YEAR
        ) = FLATTENED_PRODUCT_DEVELOPMENT_BOM_LINE_ITEMS_FLAT_V.CYCLE_YEAR
        AND SPENDCUBE_BOMS.PROD_CD IS NULL
),
BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM AS (
    SELECT BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID,
        BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.CYCLE_YEAR,
        BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.BILL_OF_MATERIAL_SOURCE,
        ARRAY_AGG(
            OBJECT_CONSTRUCT(
                'usageUom',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.USAGE_UNIT_OF_MEASURE,
                'grossUsage',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.NET_USAGE + COALESCE(
                    BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.WASTE_USAGE,
                    0
                ),
                'netUsage',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.NET_USAGE,
                'materialSection',
                upper(
                    BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.BILL_OF_MATERIALS_SECTION_NAME
                ),
                'materialUseDetail',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.PART_NAME,
                'lineItemNumber',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.BOM_LINE_ITEM_NUMBER,
                'material',
                OBJECT_CONSTRUCT(
                    'supplied_material',
                    SUPPLIED_MATERIAL_INFO.INFO,
                    'footprint',
                    SUPPLIED_MATERIAL_FOOTPRINT_INFO.FOOTPRINT
                ),
                'defectRate',
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.DEFECTIVE_LOSS_PERCENTAGE
            )
        ) AS LINE_ITEMS
    FROM BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL
        LEFT JOIN (
            SELECT SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID,
                OBJECT_CONSTRUCT(
                    'dimensions',
                    OBJECT_CONSTRUCT(
                        'g1000pcs',
                        ANY_VALUE(GRAMS_PER_THOUSAND_PIECES),
                        'heightMm',
                        ANY_VALUE(HEIGHT_MM),
                        'thicknessMm',
                        ANY_VALUE(THICKNESS_MM),
                        'widthMm',
                        ANY_VALUE(WIDTH_MM),
                        'gramsPerSquareMeter',
                        ANY_VALUE(GRAMS_PER_SQUARE_METER),
                        'gsm',
                        ANY_VALUE(GRAMS_PER_SQUARE_METER),
                        'widthCm',
                        ANY_VALUE(WIDTH_CM),
                        'widthIndicator',
                        ANY_VALUE(WIDTH_INDICATOR_NAME),
                        'lengthMm',
                        ANY_VALUE(LENGTH_MM),
                        'heightCm',
                        ANY_VALUE(HEIGHT_MM),
                        'lengthCm',
                        ANY_VALUE(LENGTH_CM),
                        'gramsPerLinearMeter',
                        ANY_VALUE(GRAMS_PER_LINEAR_METER),
                        'gramsPerThousandPieces',
                        ANY_VALUE(GRAMS_PER_THOUSAND_PIECES),
                        'gramsPerLinearYard',
                        ANY_VALUE(GRAMS_PER_LINEAR_YARD)
                    ),
                    'endUse',
                    ANY_VALUE(SUPPLIED_MATERIAL.END_USE_NAME),
                    'id',
                    OBJECT_CONSTRUCT(
                        'legacyCode',
                        ANY_VALUE(LEGACY_CODE),
                        'matId',
                        ANY_VALUE(SUPPLIED_MATERIAL.MATERIAL_ID),
                        'suppliedMatId',
                        ANY_VALUE(SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID),
                        'pdmNumber',
                        ANY_VALUE(PDM_NUMBER),
                        'mcsNumber',
                        ANY_VALUE(MATERIAL_CONTENT_SPECIFICATION_NUMBER)
                    ),
                    'matCntnt',
                    ARRAY_AGG(
                        OBJECT_CONSTRUCT(
                            'type',
                            CONTENT.TYPE_NAME,
                            'source',
                            CONTENT.SOURCE_NAME,
                            'pct',
                            CONTENT.PERCENTAGE
                        )
                    ),
                    'matItemName',
                    REGEXP_REPLACE(
                        ANY_VALUE(ITEM_NAME),
                        '[\u0000-\u0009\u000b-\u000c\u000e-\u001f\u007f-\u009f]'
                    ),
                    'matType',
                    ANY_VALUE(MAT_TYPE.ITEMS),
                    'matItemDesc',
                    REGEXP_REPLACE(
                        ANY_VALUE(PARENT.ITEM_DESCRIPTION),
                        '[\u0000-\u0009\u000b-\u000c\u000e-\u001f\u007f-\u009f]'
                    ),
                    'textileConstrType',
                    ANY_VALUE(TEXTILE_CONSTRUCTION_TYPE_NAME),
                    'family',
                    ANY_VALUE(FAMILY_NAME),
                    'legacyMatName',
                    REGEXP_REPLACE(
                        ANY_VALUE(LEGACY_MATERIAL_NAME),
                        '[\u0000-\u0009\u000b-\u000c\u000e-\u001f\u007f-\u009f]'
                    ),
                    'matTechnologies',
                    ANY_VALUE(MAT_TECH.ITEMS),
                    'methodOfMake',
                    ANY_VALUE(METHOD_OF_MAKE_NAME),
                    'component',
                    OBJECT_CONSTRUCT(
                        'constType',
                        ANY_VALUE(COMPONENT_CONSTRUCTION_TYPE),
                        'hardSoftComp',
                        ANY_VALUE(COMPONENT_HARD_SOFT),
                        'teethType',
                        ANY_VALUE(ZIPPER_TEETH_TYPE_NAME)
                    ),
                    'supplier',
                    OBJECT_CONSTRUCT(
                        'id',
                        ANY_VALUE(SUPPLIED_MATERIAL_LOCATION.SUPPLIER_ID),
                        'liasonOffice',
                        ANY_VALUE(
                            SUPPLIED_MATERIAL_LOCATION.RESPONSIBLE_LIAISON_OFFICE_NAME
                        ),
                        'locationCode',
                        ANY_VALUE(SUPPLIED_MATERIAL_LOCATION.LEGACY_LOCATION_CODE),
                        'locationId',
                        ANY_VALUE(SUPPLIED_MATERIAL_LOCATION.LOCATION_ID),
                        'locationName',
                        ANY_VALUE(SUPPLIED_MATERIAL_LOCATION.LOCATION_NAME),
                        'name',
                        ANY_VALUE(SUPPLIED_MATERIAL_LOCATION.NAME)
                    )
                ) AS INFO
            FROM FND_MATERIAL.SUPPLIED_MATERIAL SUPPLIED_MATERIAL
                LEFT JOIN FND_MATERIAL.SUPPLIED_MATERIAL_CONTENT CONTENT ON CONTENT.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
                LEFT JOIN FND_MATERIAL.MATERIAL PARENT ON PARENT.MATERIAL_ID = SUPPLIED_MATERIAL.MATERIAL_ID
                LEFT JOIN FND_MATERIAL.SUPPLIED_MATERIAL_LOCATION SUPPLIED_MATERIAL_LOCATION ON SUPPLIED_MATERIAL_LOCATION.SUPPLIER_ID = SUPPLIED_MATERIAL.SUPPLIER_ID
                AND SUPPLIED_MATERIAL_LOCATION.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
                LEFT JOIN (
                    SELECT ARRAY_AGG(NAME) AS ITEMS,
                        SUPPLIED_MATERIAL_TECHNOLOGY.SUPPLIED_MATERIAL_ID
                    FROM FND_MATERIAL.SUPPLIED_MATERIAL_TECHNOLOGY SUPPLIED_MATERIAL_TECHNOLOGY
                    GROUP BY SUPPLIED_MATERIAL_TECHNOLOGY.SUPPLIED_MATERIAL_ID
                ) MAT_TECH ON MAT_TECH.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
                LEFT JOIN (
                    SELECT ARRAY_AGG(NAME) WITHIN GROUP (
                            ORDER BY SUPPLIED_MATERIAL_TYPE_ORDINAL
                        ) AS ITEMS,
                        SUPPLIED_MATERIAL_TYPE.SUPPLIED_MATERIAL_ID
                    FROM FND_MATERIAL.SUPPLIED_MATERIAL_TYPE AS SUPPLIED_MATERIAL_TYPE
                    GROUP BY SUPPLIED_MATERIAL_TYPE.SUPPLIED_MATERIAL_ID
                ) MAT_TYPE ON MAT_TYPE.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
            GROUP BY SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
        ) AS SUPPLIED_MATERIAL_INFO ON SUPPLIED_MATERIAL_INFO.SUPPLIED_MATERIAL_ID = BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.SUPPLIED_MATERIAL_ID
        LEFT JOIN (
            SELECT SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID,
                OBJECT_CONSTRUCT(
                    'name',
                    ANY_VALUE(FOOTPRINT.NAME),
                    'description',
                    ANY_VALUE(FOOTPRINT.DESCRIPTION),
                    'score',
                    ANY_VALUE(FOOTPRINT.SCORE),
                    'scores',
                    ANY_VALUE(MEASURES.ITEMS)
                ) AS FOOTPRINT
            FROM FND_MATERIAL.SUPPLIED_MATERIAL SUPPLIED_MATERIAL
            LEFT JOIN FND_MATERIAL.SUPPLIED_MATERIAL_FOOTPRINT SUPPLIED_MATERIAL_FOOTPRINT ON SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL_FOOTPRINT.SUPPLIED_MATERIAL_ID
            LEFT JOIN FND_MATERIAL.FOOTPRINT FOOTPRINT ON SUPPLIED_MATERIAL_FOOTPRINT.FOOTPRINT_ID = FOOTPRINT.FOOTPRINT_ID
            AND SUPPLIED_MATERIAL_FOOTPRINT.CALCULATOR_VERSION = FOOTPRINT.CALCULATOR_VERSION
            LEFT JOIN (
                SELECT SUPPLIED_MATERIAL_ID,
                    ARRAY_AGG(
                        OBJECT_CONSTRUCT(
                            'midpoint',
                            MIDPOINT,
                            'name',
                            NAME,
                            'score',
                            SCORE
                        )
                    ) AS ITEMS,
                    SUM(SCORE) AS SCORE
                FROM (
                    SELECT SUPPLIED_MATERIAL_ID,
                        MEASURE.NAME,
                        SUM(SHARE * MIDPOINT) AS MIDPOINT,
                        SUM(SHARE * SCORE) AS SCORE
                    FROM FND_MATERIAL.SUPPLIED_MATERIAL_FOOTPRINT_PROCESS
                    LEFT JOIN FND_MATERIAL.FOOTPRINT_PROCESS_MEASURE
                        ON SUPPLIED_MATERIAL_FOOTPRINT_PROCESS.FOOTPRINT_ID = FOOTPRINT_PROCESS_MEASURE.FOOTPRINT_ID
                        AND SUPPLIED_MATERIAL_FOOTPRINT_PROCESS.PROCESS_ID = FOOTPRINT_PROCESS_MEASURE.PROCESS_ID
                        AND SUPPLIED_MATERIAL_FOOTPRINT_PROCESS.CALCULATOR_VERSION = FOOTPRINT_PROCESS_MEASURE.CALCULATOR_VERSION
                    LEFT JOIN FND_MATERIAL.MEASURE
                        ON FOOTPRINT_PROCESS_MEASURE.MEASURE_ID = MEASURE.MEASURE_ID
                    WHERE SUPPLIED_MATERIAL_FOOTPRINT_PROCESS.CALCULATOR_VERSION = '0.0.0'
                    GROUP BY SUPPLIED_MATERIAL_ID, MEASURE.NAME
                )
                GROUP BY SUPPLIED_MATERIAL_ID
            ) MEASURES ON MEASURES.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL_FOOTPRINT.SUPPLIED_MATERIAL_ID
            WHERE SUPPLIED_MATERIAL_FOOTPRINT.CALCULATOR_VERSION = '0.0.0'
                OR SUPPLIED_MATERIAL_FOOTPRINT.CALCULATOR_VERSION IS NULL
            GROUP BY SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
        ) AS SUPPLIED_MATERIAL_FOOTPRINT_INFO ON SUPPLIED_MATERIAL_FOOTPRINT_INFO.SUPPLIED_MATERIAL_ID = BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.SUPPLIED_MATERIAL_ID
    WHERE NOT (
            -- Double percents are required here because the dialect engine
            -- which executes this uses formatting for which an unescaped percent
            -- sign indicates the start of a parameter
            COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.MATERIAL_ITEM_PLACEHOLDER_DESCRIPTION,
                ''
            ) LIKE '1538|%%'
            OR COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.MATERIAL_ITEM_PLACEHOLDER_DESCRIPTION,
                ''
            ) LIKE '1537|%%'
            OR COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.COLOR_PLACEHOLDER_DESCRIPTION,
                ''
            ) LIKE '1538|%%'
            OR COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.COLOR_PLACEHOLDER_DESCRIPTION,
                ''
            ) LIKE '1537|%%'
            OR COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.COMPONENT_LINE_ITEM_LIST,
                ''
            ) LIKE '%%1538|%%'
            OR COALESCE(
                BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.COMPONENT_LINE_ITEM_LIST,
                ''
            ) LIKE '%%1537|%%'
        )
    GROUP BY PRODUCT_DEVELOPMENT_BOM_UUID,
        BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.CYCLE_YEAR,
        BILL_OF_MATERIAL_CYCLE_YEAR_MATERIAL.BILL_OF_MATERIAL_SOURCE
)
SELECT BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID AS BUILD_OF_MATERIAL_ID,
    BILL_OF_MATERIAL.CYCLE_YEAR AS SEASON_YEAR_CODE,
    ANY_VALUE(
        IFF(
            BILL_OF_MATERIAL.STYLE IS NULL,
            NULL,
            BILL_OF_MATERIAL.STYLE || '-' || BILL_OF_MATERIAL.COLORWAY
        )
    ) as PRODUCT_CODE,
    ANY_VALUE(AGE) as AGE_GROUP,
    ANY_VALUE(PRODUCT_LINE.CATEGORY) as CATEGORY,
    ANY_VALUE(CLASSIFICATION) as CLASSIFICATION,
    ANY_VALUE(BILL_OF_MATERIAL.COLORWAY) as COLORWAY,
    ANY_VALUE(DEV_TEAM) as DEVELOPMENT_TEAM,
    ANY_VALUE(BILL_OF_MATERIAL.DIVISION) as DIVISION,
    ANY_VALUE(BILL_OF_MATERIAL.FCTY) as FACTORY,
    ANY_VALUE(FIT) as FIT,
    ANY_VALUE(GENDER) as GENDER,
    ANY_VALUE(MARKETING_TYPE) as MARKETING_TYPE,
    SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) as SEASON,
    TO_NUMBER(SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 3, 2)) + 2000 as YEAR,
    ANY_VALUE(SILHOUETTE) as SILHOUETTE,
    ANY_VALUE(STYLE_NAME) as STYLE_NAME,
    ANY_VALUE(
        IFF(
            BILL_OF_MATERIAL.STYLE IS NULL,
            NULL,
            BILL_OF_MATERIAL.STYLE
        )
    ) as STYLE_NUMBER,
    OBJECT_CONSTRUCT(
        'milestone',
        ANY_VALUE(COST_BREAKDOWN.MILESTONE),
        'technicalDifficulty',
        ANY_VALUE(COST_BREAKDOWN.TECH_DFCLTY),
        'importExportKg',
        ANY_VALUE(WEIGHTS.NET_NET),
        'demandPlanVolume',
        ROUND(
            COALESCE(SUM(DP_VOLUME / ARRAY_SIZE(BOM_IDS)), 0)
        ),
        'factory',
        ANY_VALUE(BILL_OF_MATERIAL.FCTY),
        'factoryCountry',
        ANY_VALUE(FCTY.FCTY_CTRY),
        'age',
        ANY_VALUE(AGE),
        'gender',
        ANY_VALUE(GENDER),
        'silhouette',
        ANY_VALUE(SILHOUETTE),
        'styleName',
        ANY_VALUE(STYLE_NAME),
        'classification',
        ANY_VALUE(CLASSIFICATION),
        'category',
        ANY_VALUE(PRODUCT_LINE.CATEGORY),
        'fit',
        ANY_VALUE(FIT),
        'developmentTeam',
        ANY_VALUE(DEV_TEAM),
        'marketingType',
        ANY_VALUE(MARKETING_TYPE),
        'businessOrganization',
        ANY_VALUE(BUSINESS_ORGANIZATION),
        'sponsor',
        ANY_VALUE(SPONSOR),
        'consumerPurpose',
        ANY_VALUE(CONSUMER_PURPOSE),
        'consumerFocus',
        ANY_VALUE(CONSUMER_FOCUS),
        'teamName',
        ANY_VALUE(TEAM_NAME),
        'modelId',
        ANY_VALUE(MODEL_ID),
        'modelName',
        ANY_VALUE(MODEL_NAME),
        'consumerUse',
        ANY_VALUE(CONSUMER_USE),
        'consumerGroup',
        ANY_VALUE(CONSUMER_GROUP),
        'subCategory',
        ANY_VALUE(SUB_CATEGORY),
        'materialIntent',
        ANY_VALUE(MATERIAL_INTENT),
        'construction',
        ANY_VALUE(CONSTRUCTION),
        'productTier',
        ANY_VALUE(PRODUCT_TIER),
        'marketingInitiative',
        ANY_VALUE(MARKETING_INITIATIVE),
        'moddelOfferingGroup',
        ANY_VALUE(MO_GROUP),
        'lineEvolution',
        ANY_VALUE(LINE_EVOLUTION),
        'carryoverStatus',
        ANY_VALUE(CARRYOVER_STATUS),
        'plmName',
        ANY_VALUE(PLM_NAME),
        'plmCode',
        ANY_VALUE(PLM_CODE),
        'consumerConstructDimensionName',
        ANY_VALUE(CONSUMER_CONSTRUCT_DIMENSION_NAME),
        'consumerConstructGlobalConsumerOffenseName',
        ANY_VALUE(CONSUMER_CONSTRUCT_GLOBAL_CONSUMER_OFFENSE_NAME),
        'productPlanningAgeGenderName',
        ANY_VALUE(PRODUCT_PLANNING_AGE_GENDER_NAME),
        'productPlanningDivisionName',
        ANY_VALUE(PRODUCT_PLANNING_DIVISION_NAME),
        'productPlanningIntendedUseName',
        ANY_VALUE(PRODUCT_PLANNING_INTENDED_USE_NAME),
        'productPlanningStructureName',
        ANY_VALUE(PRODUCT_PLANNING_STRUCTURE_NAME),
        'productPlanningSilhouetteName',
        ANY_VALUE(PRODUCT_PLANNING_SILHOUETTE_NAME),
        'productPlanningSubSilhouetteName',
        ANY_VALUE(PRODUCT_PLANNING_SUB_SILHOUETTE_NAME),
        'productOfferingStatusIndicator',
        ANY_VALUE(PRODUCT_OFFERING_STATUS_INDICATOR),
        'division',
        ANY_VALUE(BILL_OF_MATERIAL.DIVISION),
        'season',
        SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2),
        'seasonYear',
        TO_NUMBER(SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 3, 2)) + 2000,
        'quarter',
        CASE
            WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'FA' THEN 1
            WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'HO' THEN 2
            WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'SP' THEN 3
            WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'SU' THEN 4
        END,
        'ssyy',
        BILL_OF_MATERIAL.CYCLE_YEAR,
        'bomId',
        BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID,
        'bomIdentifier',
        ANY_VALUE(BILL_OF_MATERIAL.BOM_IDENTIFIER),
        'productUuid',
        ANY_VALUE(BILL_OF_MATERIAL.PRODUCT_UUID),
        'productCode',
        ANY_VALUE(
            IFF(
                BILL_OF_MATERIAL.STYLE IS NULL,
                NULL,
                BILL_OF_MATERIAL.STYLE || '-' || BILL_OF_MATERIAL.COLORWAY
            )
        ),
        'styleNumber',
        ANY_VALUE(
            IFF(
                BILL_OF_MATERIAL.STYLE IS NULL,
                NULL,
                BILL_OF_MATERIAL.STYLE
            )
        ),
        'fiscalYear',
        (
            TO_NUMBER(SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 3, 2)) + 2000 + IFF(
                SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) IN ('FA', 'HO'),
                1,
                0
            )
        ),
        'productSeasonId',
        ANY_VALUE(
            IFF(
                BILL_OF_MATERIAL.STYLE IS NULL,
                BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID,
                BILL_OF_MATERIAL.STYLE || '-' || BILL_OF_MATERIAL.COLORWAY
            ) || '/' || TO_VARCHAR(
                TO_NUMBER(SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 3, 2)) + 2000 + IFF(
                    SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) IN ('FA', 'HO'),
                    1,
                    0
                )
            ) || '/' || CASE
                WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'FA' THEN 1
                WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'HO' THEN 2
                WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'SP' THEN 3
                WHEN SUBSTR(BILL_OF_MATERIAL.CYCLE_YEAR, 1, 2) = 'SU' THEN 4
            END || '/' || BILL_OF_MATERIAL.FCTY
        ),
        'bomSource',
        ANY_VALUE(BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM.BILL_OF_MATERIAL_SOURCE),
        'lineItems',
        ANY_VALUE(BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM.LINE_ITEMS)
    ) AS DATA
FROM BILL_OF_MATERIAL
    LEFT JOIN (
        SELECT *,
            TO_VARCHAR(FLATTENED_BOM_IDS.VALUE) AS PRODUCT_DEVELOPMENT_BOM_UUID
        FROM DP_VOLUME,
            TABLE(FLATTEN(DP_VOLUME.BOM_IDS)) FLATTENED_BOM_IDS
    ) VOLUME ON BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID = VOLUME.PRODUCT_DEVELOPMENT_BOM_UUID
    AND BILL_OF_MATERIAL.CYCLE_YEAR = VOLUME.CYCLE_YEAR
    LEFT JOIN WEIGHTS ON WEIGHTS.STYLE = BILL_OF_MATERIAL.STYLE
    LEFT JOIN PRODUCT_LINE ON PRODUCT_LINE.STYLE = BILL_OF_MATERIAL.STYLE
    AND PRODUCT_LINE.CYCLE_YEAR = BILL_OF_MATERIAL.CYCLE_YEAR
    AND PRODUCT_LINE.COLORWAY = BILL_OF_MATERIAL.COLORWAY
    LEFT JOIN COST_BREAKDOWN ON COST_BREAKDOWN.RANK = 1
    AND COST_BREAKDOWN.FCTY = BILL_OF_MATERIAL.FCTY
    AND COST_BREAKDOWN.COLORWAY_IDENTIFIER = BILL_OF_MATERIAL.COLORWAY_IDENTIFIER
    AND COST_BREAKDOWN.BOM_HDR_ID = BILL_OF_MATERIAL.BOM_IDENTIFIER
    LEFT JOIN PES_ARIA_PRODUCT_PROD.PROCESSED.PCX_FCTY_V FCTY ON FCTY.FCTY_LGCY_CD = BILL_OF_MATERIAL.FCTY
    LEFT JOIN BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM ON BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM.PRODUCT_DEVELOPMENT_BOM_UUID = BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID
    AND BILL_OF_MATERIAL_CYCLE_YEAR_LINE_ITEM.CYCLE_YEAR = BILL_OF_MATERIAL.CYCLE_YEAR
GROUP BY BILL_OF_MATERIAL.PRODUCT_DEVELOPMENT_BOM_UUID,
    BILL_OF_MATERIAL.CYCLE_YEAR
