[metadata]
name = docker-utilities
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = Utilities for building and deploying My Docker images
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/docker-utilities

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	docker_utilities
install_requires =
	cerberus-assistant>=0.3,<2.0

[options.entry_points]
console_scripts =
	docker-utilities = docker_utilities.__main__:main
	du = docker_utilities.__main__:main

[options.package_data]
* = py.typed
