[metadata]
name = enablon-ingress-client
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/sample-client-sdks/enablon-ingress-client

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	enablon_ingress_client
install_requires =
	oapi~=1.62
	cerberus-assistant~=1.0

[options.package_data]
* = py.typed
