[metadata]
name = map-airflow-client
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description = Developer tools for Airflow
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/sample-client-sdks/open-api-clients/when-openapi-spec-not-accurate/map-airflow-client

[options]
python_requires = ~=3.7
packages =
	map_airflow_client
	map_airflow_client.experimental
	map_airflow_client.v1
include_package_data = True
install_requires =
	sob~=1.50
	oapi~=1.62
	cerberus-assistant~=1.0

[options.entry_points]
console_scripts =
	map-airflow-client = map_airflow_client.__main__:main

[options.package_data]
* = py.typed
