[metadata]
name = my-datastore-etl-wrapper
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/my-datastore-etl-wrapper

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	my_datastore_etl_wrapper
install_requires =
	etl-framework
	my-datastore-orm[pyarrow]
	packaging

[options.extras_require]
spark =
	my-datastore-orm[pyspark]
snowflake =
	my-datastore-orm[snowflake]
postgresql =
	my-datastore-orm[postgresql]
all =
	my-datastore-orm[pyspark]
	my-datastore-orm[snowflake]
	my-datastore-orm[postgresql]

[options.entry_points]
console_scripts =
	my-datastore-etl-wrapper = my_datastore_etl_wrapper.__main__:main

[options.package_data]
* = py.typed
