[tox]
parallel_show_output = True
envlist = black, flake8, mypy, isort, pytest-snowflake, pytest-postgresql, pytest-local, pytest-local-not-spark

[testenv]
install_command =
	python3 -m pip install -c requirements.txt {opts} {packages}
passenv =
	HUDSON_URL
	CI
	LOCALSTACK_HOSTNAME
	SPARK_LOCAL_IP
	AWS_WEB_IDENTITY_TOKEN_FILE
	AWS_ROLE_ARN
	DOCKER_*
setenv =
	PIP_EXTRA_INDEX_URL=NONE
	OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
	AIRFLOW_GPL_UNIDECODE=YES

[testenv:pytest-local]
extras =
	spark
deps =
	file-system-client
	pytest
commands =
	py.test -W error::sqlalchemy.exc.SADeprecationWarning -m spark tests/test_local.py

[testenv:pytest-local-not-spark]
deps =
	file-system-client
	pytest
commands =
	py.test -W error::sqlalchemy.exc.SADeprecationWarning -m "not spark" tests/test_local.py

[testenv:pytest-snowflake]
extras =
	spark
	snowflake
deps =
	pytest
commands_pre =
	orm-framework spark install-snowflake-jdbc-driver
commands =
	py.test -W error::sqlalchemy.exc.SADeprecationWarning tests/test_snowflake.py

[testenv:pytest-postgresql]
install_command =
	python3 -m pip install {opts} {packages}
extras =
	postgresql
deps =
	pytest
commands =
	py.test -W error::sqlalchemy.exc.SADeprecationWarning tests/test_postgresql.py

[testenv:pytest-transformer]
deps =
	pytest
commands =
	py.test -W error::sqlalchemy.exc.SADeprecationWarning tests/test_transformer.py

[testenv:black]
deps =
	black
commands =
	black --check .

[testenv:flake8]
deps =
	flake8
commands =
	flake8

[testenv:mypy]
extras =
	all
deps =
	mypy
	pyspark
	pytest
commands =
	mypy --install-types --non-interactive
	mypy

[testenv:isort]
deps =
	isort
commands =
	isort -c .
