"""SPAM-334: create new table SUPPLIED_MATERIAL

Revision ID: 6fb724bd82e7
Revises: 6b19e298affb
Create Date: 2024-03-22 12:15:19.211038
"""

import analytics_orm.types  # type: ignore
import sqlalchemy.sql.sqltypes  # type: ignore
import sys
from alembic import op  # type: ignore
from my_api_model.dialects.postgresql import (
    create_environment,
    grant_environment_permissions,
)
from sqlalchemy.engine import (  # type: ignore
    Connectable,
    Connection,
    Transaction,
)

# revision identifiers, used by Alembic.
revision = "6fb724bd82e7"
down_revision = "6b19e298affb"
branch_labels = None
depends_on = None


def _attempt_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SUPPLIED_MATERIAL",
        sqlalchemy.Column(
            "SUPPLIED_MATERIAL_ID",
            sqlalchemy.Integer(),
            autoincrement=False,
            nullable=False,
        ),
        sqlalchemy.Column(
            "FOOTPRINT", analytics_orm.types.Object(), nullable=True
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "SUPPLIED_MATERIAL_ID", name=op.f("PK_SUPPLIED_MATERIAL")
        ),
        databricks_schema=None,
        postgresql_schema=None,
        snowflake_schema="PUBLIC",
        sqlite_schema=None,
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Transaction = connection.begin()
    try:
        _attempt_upgrade()
        if "head" in sys.argv:
            create_environment(bind=bind, checkfirst=True)
        else:
            grant_environment_permissions(bind=bind)
        transaction.commit()
    except:  # noqa
        transaction.rollback()
        raise


def _attempt_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SUPPLIED_MATERIAL")
    # ### end Alembic commands ###


def downgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Transaction = connection.begin()
    try:
        _attempt_downgrade()
        transaction.commit()
    except:  # noqa
        transaction.rollback()
        raise
