[metadata]
name = databricks-jobs
version = 0.0.0
author_email = reddy.siddartha53@gmail.com
description =
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/databricks-jobs

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	databricks_jobs
install_requires =
	databricks-sdk~=0.24
	cerberus-assistant~=1.0
	tomli~=2.0

[options.entry_points]
console_scripts =
	databricks-jobs = databricks_jobs.__main__:main

[options.package_data]
* = py.typed
