[metadata]
name = sample-snowflake2postgresql-etl
version = 0.28.1
author_email = reddy.siddartha53@gmail.com
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/sample-snowflake2postgresql-etl

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	sample_snowflake2postgresql_etl
install_requires =
	my-datastore-etl[postgresql,snowflake]
	my-api-model
	more-itertools<11.0,>=9.1

[options.entry_points]
console_scripts =
	sample-snowflake2postgresql-etl = sample_snowflake2postgresql_etl.__main__:main

[options.package_data]
* = py.typed
sample_snowflake2postgresql_etl = _snowflake_queries/*.sql
