"""sdf-1923

Revision ID: 728ae8bc962f
Revises: c88ed7b5e9ed
Create Date: 2024-04-26 06:36:25.890505
"""

from typing import Optional

# flake8: noqa: E501
import sqlalchemy.sql.sqltypes  # type: ignore
from sqlalchemy.engine import (  # type: ignore
    Connectable,
    Connection,
    Transaction,
)

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "728ae8bc962f"
down_revision = "c88ed7b5e9ed"
branch_labels = None
depends_on = None


def _attempt_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ENABLON_INGRESS_FEEDBACK",
        sqlalchemy.Column(
            "ENTITY_DIVISION_CD", sqlalchemy.String(), nullable=False
        ),
        sqlalchemy.Column("INDICATOR_CD", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column(
            "REPORTING_PERIOD_YEAR_NBR", sqlalchemy.Integer(), nullable=False
        ),
        sqlalchemy.Column(
            "REPORTING_PERIOD_MONTH_NBR", sqlalchemy.Integer(), nullable=False
        ),
        sqlalchemy.Column(
            "REPORTING_PERIOD_DAY_NBR", sqlalchemy.Integer(), nullable=False
        ),
        sqlalchemy.Column(
            "INDICATOR_VALUE_TXT", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_VALUE_UOM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_COMMENT_TXT", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_VALUE_UPDATE_SUCCESSFUL_IND",
            sqlalchemy.Boolean(),
            nullable=True,
        ),
        sqlalchemy.Column("FEEDBACK_TXT", sqlalchemy.String(), nullable=True),
        sqlalchemy.PrimaryKeyConstraint(
            "ENTITY_DIVISION_CD",
            "INDICATOR_CD",
            "REPORTING_PERIOD_YEAR_NBR",
            "REPORTING_PERIOD_MONTH_NBR",
            "REPORTING_PERIOD_DAY_NBR",
            name=op.f("PK_ENABLON_INGRESS_FEEDBACK"),
        ),
        schema="FND_ENABLON",
        snowflake_schema="FND_ENABLON",
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Optional[Transaction] = getattr(
        connection, "begin", lambda: None
    )()
    try:
        _attempt_upgrade()
        if transaction is not None:
            transaction.commit()
    except Exception:
        if transaction is not None:
            transaction.rollback()
        raise


def _attempt_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ENABLON_INGRESS_FEEDBACK", schema="FND_ENABLON")
    # ### end Alembic commands ###


def downgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Optional[Transaction] = getattr(
        connection, "begin", lambda: None
    )()
    try:
        _attempt_downgrade()
        if transaction is not None:
            transaction.commit()
    except Exception:
        if transaction is not None:
            transaction.rollback()
        raise
