"""sample-migration

Revision ID: 8438c275718b
Revises:
Create Date: 2024-02-20 12:45:44.361481
"""

from typing import Optional

import sqlalchemy.sql.sqltypes  # type: ignore
from sqlalchemy.engine import (  # type: ignore
    Connectable,
    Connection,
    Transaction,
)

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "8438c275718b"
down_revision = None
branch_labels = None
depends_on = None


def _attempt_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SAMPLE_TABLE",
        sqlalchemy.Column("REF_ID", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column(
            "REPORTING_PERIOD_DT", sqlalchemy.DateTime(), nullable=False
        ),
        sqlalchemy.Column(
            "INDICATOR_ID", sqlalchemy.Integer(), nullable=False
        ),
        sqlalchemy.Column("REF_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("REF_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("LEVEL_NBR", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("ENTITY_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("ENTITY_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("ENTITY_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("CORPORATE_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("CORPORATE_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("CORPORATE_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("BRAND_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("BRAND_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("BRAND_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "BUSINESS_FUNCTION_ID", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "BUSINESS_FUNCTION_CD", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "BUSINESS_FUNCTION_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("DIVISION_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("DIVISION_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("DIVISION_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("GEOGRAPHY_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("GEOGRAPHY_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("GEOGRAPHY_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("CONTINENT_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("LEASE_NBR", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("ADDRESS", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("CITY_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("STATE_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "STATE_REGION_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("COUNTRY_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("ZIP_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "GEOGRAPHICAL_AXIS", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("LATITUDE", sqlalchemy.Float(), nullable=True),
        sqlalchemy.Column("LONGITUDE", sqlalchemy.Float(), nullable=True),
        sqlalchemy.Column("AREA_IN_SQFT", sqlalchemy.Float(), nullable=True),
        sqlalchemy.Column("KEYWORD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "ENTITY_STATUS_DESC", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "IMPACT_AREA_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "SECONDARY_IMPACT_AREA_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("SCOPE_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("PROTOCOL_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "GREENHOUSE_GAS_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "CONSUMPTION_GROUP_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "EMISSION_FACTOR_CD", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "EMISSION_FACTOR_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "EF_EFFECTIVE_DT", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("EF_UOM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "INDICATOR_REFERENTIAL_ID", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_REFERENTIAL_CD", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_REFERENTIAL_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_BUSINESS_FUNCTION_ID",
            sqlalchemy.Integer(),
            nullable=True,
        ),
        sqlalchemy.Column(
            "INDICATOR_BUSINESS_FUNCTION_CD",
            sqlalchemy.String(),
            nullable=True,
        ),
        sqlalchemy.Column(
            "INDICATOR_BUSINESS_FUNCTION_NM",
            sqlalchemy.String(),
            nullable=True,
        ),
        sqlalchemy.Column(
            "IMPACT_AREA_QUESTIONNAIRE_ID", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "IMPACT_AREA_QUESTIONNAIRE_CD", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "IMPACT_AREA_QUESTIONNAIRE_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("INDICATOR_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("INDICATOR_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "INDICATOR_ACTIVE_FLAG", sqlalchemy.Boolean(), nullable=True
        ),
        sqlalchemy.Column("CAMPAIGN_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("CAMPAIGN_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "INDICATOR_TYPE_CD", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_TYPE_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_NUMERATOR", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "INDICATOR_DENOMINATOR", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("FREQUENCY_ID", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("FREQUENCY_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "REPORTING_PERIOD_FISCAL_YEAR_NBR",
            sqlalchemy.Integer(),
            nullable=True,
        ),
        sqlalchemy.Column(
            "REPORTING_PERIOD_FISCAL_QUARTER_NBR",
            sqlalchemy.Integer(),
            nullable=True,
        ),
        sqlalchemy.Column(
            "REPORTING_PERIOD_YEAR_NBR", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "REPORTING_PERIOD_MONTH_NBR", sqlalchemy.Integer(), nullable=True
        ),
        sqlalchemy.Column(
            "VALUE_UNIVERSAL_NBR", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("BASE_UNIT_CD", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column("BASE_UNIT_NM", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "CONVERTED_VALUE_NBR", sqlalchemy.Float(), nullable=True
        ),
        sqlalchemy.Column(
            "CONVERTED_UNIT_CD", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "CONVERTED_UNIT_NM", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column(
            "CALCULATED_SUM_IND", sqlalchemy.String(), nullable=True
        ),
        sqlalchemy.Column("COMMENT", sqlalchemy.String(), nullable=True),
        sqlalchemy.PrimaryKeyConstraint(
            "REF_ID",
            "REPORTING_PERIOD_DT",
            "INDICATOR_ID",
            name=op.f("PK_SAMPLE_TABLE"),
        ),
        schema="FNS_SAMPLE_SNOWFLAKE_SCHEMA",
        sqlite_table_name="",
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Optional[Transaction] = getattr(
        connection, "begin", lambda: None
    )()
    try:
        _attempt_upgrade()
        if transaction is not None:
            transaction.commit()
    except Exception:
        if transaction is not None:
            transaction.rollback()
        raise


def _attempt_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        "ENABLON_EGRESS_IMPACT_AREAS_COMBINED", schema="SAMPLE_SNOWFLAKE_SCHEMA"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    bind: Connectable = op.get_bind()
    connection: Connection = bind.connect()
    transaction: Optional[Transaction] = getattr(
        connection, "begin", lambda: None
    )()
    try:
        _attempt_downgrade()
        if transaction is not None:
            transaction.commit()
    except Exception:
        if transaction is not None:
            transaction.rollback()
        raise
