[metadata]
name = file-system-client
version = 0.0.a1
author_email = reddy.siddartha53@gmail.com
description = File System Client
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/file-system-client

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	file_system_client

[options.package_data]
* = py.typed

