[metadata]
name = file-system-client
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = File System Client
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/file-system-client

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	file_system_client

[options.package_data]
* = py.typed

[options.extras_require]
s3 =
	boto3~=1.34
localstack =
	localstack-client~=2.5
all =
	boto3~=1.34
	localstack-client~=2.5
