[tox]
requires =
	pip
envlist = isort, black, flake8, mypy, pytest-s3-oidc, pytest-s3, pytest-local

[testenv]
passenv =
	USER
	HOME
	HUDSON_URL
	CI
	AWS_WEB_IDENTITY_TOKEN_FILE
	AWS_ROLE_ARN
	DOCKER_*
setenv =
	PIP_EXTRA_INDEX_URL = NONE

[testenv:pytest-s3-oidc]
deps =
	pytest
commands =
	py.test -s -vv tests/test_s3_oidc.py

[testenv:pytest-s3]
deps =
	pytest
commands =
	py.test -s -vv tests/test_s3.py

[testenv:pytest-local]
deps =
	pytest
commands =
	py.test -s -vv tests/test_local.py

[testenv:black]
deps =
	black
commands =
	black --check .

[testenv:flake8]
deps =
	flake8
commands =
	flake8

[testenv:mypy]
deps =
	mypy
commands =
	mypy --install-types --non-interactive
	mypy

[testenv:isort]
deps =
	isort
commands =
	isort -c .
