[metadata]
name = mail-client
version = 0.0.0a0
author_email = reddy.siddartha53@gmail.com
description = An SMTP email client.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/siddartham/data-engineering-ecosystem/mail-client

[options]
python_requires = ~=3.8
include_package_data = True
packages =
	mail_client
install_requires =
	cerberus-assistant

[options.entry_points]
console_scripts =
	mail-client = mail_client.__main__:main

[options.package_data]
* = py.typed
