WITH COUNTRY_CTE AS (
    SELECT * FROM BCL_ENABLON.ENABLON_COUNTRY_MV
)
SELECT HO_GEOGRAPHY.ID AS REGION_ID,
    HO_GEOGRAPHY.CODE AS REGION_CODE,
    HO_GEOGRAPHY.NAME AS REGION_NAME,
    COUNTRY_CTE.COUNTRY_ID,
    COUNTRY_CTE.COUNTRY_CODE,
    COUNTRY_CTE.COUNTRY_NAME,
    COUNTRY_CTE.CONTINENT_ID,
    COUNTRY_CTE.CONTINENT_CODE,
    COUNTRY_CTE.CONTINENT_NAME
FROM FND_ENABLON.HO_GEOGRAPHY HO_GEOGRAPHY
JOIN COUNTRY_CTE ON HO_GEOGRAPHY.FRACTAL_PARENT_ID = COUNTRY_CTE.COUNTRY_ID
WHERE HO_GEOGRAPHY.FRACTAL_DEPTH = 3
