WITH CITY_CTE AS (
    SELECT * FROM BCL_ENABLON.ENABLON_CITY_MV
)
SELECT HO_GEOGRAPHY.ID AS ZIP_CODE_ID,
    HO_GEOGRAPHY.CODE AS ZIP_CODE,
    HO_GEOGRAPHY.NAME AS ZIP_CODE_NAME,
    CITY_CTE.CITY_ID,
    CITY_CTE.CITY_CODE,
    CITY_CTE.CITY_NAME,
    CITY_CTE.REGION_ID,
    CITY_CTE.REGION_CODE,
    CITY_CTE.REGION_NAME,
    CITY_CTE.COUNTRY_ID,
    CITY_CTE.COUNTRY_CODE,
    CITY_CTE.COUNTRY_NAME,
    CITY_CTE.CONTINENT_ID,
    CITY_CTE.CONTINENT_CODE,
    CITY_CTE.CONTINENT_NAME
FROM FND_ENABLON.HO_GEOGRAPHY HO_GEOGRAPHY
JOIN CITY_CTE ON HO_GEOGRAPHY.FRACTAL_PARENT_ID = CITY_CTE.CITY_ID
WHERE HO_GEOGRAPHY.FRACTAL_DEPTH = 5
