WITH SUPPLIED_MATERIAL_SUPPLIER_LOCATION_ROW_NUMBER AS (
    SELECT
    ROW_NUMBER() OVER (
        PARTITION BY SUPPLIED_MATERIAL_ID
        ORDER BY SUPPLIER_ID, LOCATION_ID DESC
    ) AS LOCATION_ROW_NUMBER,
    SUPPLIED_MATERIAL_ID,
    SUPPLIER_ID,
    NAME AS SUPPLIER_NAME,
    LEGACY_LOCATION_CODE AS SUPPLIER_LEGACY_LOCATION_CODE
    FROM FND_MATERIAL.SUPPLIED_MATERIAL_LOCATION
),
SUPPLIED_MATERIAL_SUPPLIER AS (
    SELECT
    SUPPLIED_MATERIAL_ID,
    SUPPLIER_ID,
    SUPPLIER_NAME,
    SUPPLIER_LEGACY_LOCATION_CODE
    FROM SUPPLIED_MATERIAL_SUPPLIER_LOCATION_ROW_NUMBER
    WHERE LOCATION_ROW_NUMBER = 1
),
SUPPLIED_MATERIAL_ART_TECHNIQUE_ROW_NUMBER AS (
    SELECT
    SUPPLIED_MATERIAL_ARTWORK_GRAPHIC_V.SUPPLIED_MATERIAL_ID,
    SUPPLIED_MATERIAL_ARTWORK_GRAPHIC_V.ARTWORK_TECHNIQUE_NM AS ART_TECHNIQUE,
    ROW_NUMBER() OVER (
        PARTITION BY SUPPLIED_MATERIAL_ID
        ORDER BY ARTWORK_TECHNIQUE_NM
    ) AS ART_TECHNIQUE_ROW_NUMBER
    FROM MATERIAL_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_ARTWORK_GRAPHIC_V
    WHERE ARTWORK_TECHNIQUE_NM IS NOT NULL
),
SUPPLIED_MATERIAL_ART_TECHNIQUE AS (
    SELECT
    SUPPLIED_MATERIAL_ID,
    ART_TECHNIQUE
    FROM SUPPLIED_MATERIAL_ART_TECHNIQUE_ROW_NUMBER
    WHERE ART_TECHNIQUE_ROW_NUMBER = 1
)
SELECT SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_ID,
    SUPPLIED_MATERIAL_V.MATERIAL_ID,
    SUPPLIED_MATERIAL_SUPPLIER.SUPPLIER_ID,
    SUPPLIED_MATERIAL_SUPPLIER.SUPPLIER_NAME,
    SUPPLIED_MATERIAL_SUPPLIER.SUPPLIER_LEGACY_LOCATION_CODE,
    CASE
        WHEN (
            SUPPLIED_MATERIAL_V.DIVISION_DESC = 'FOOTWEAR DIVISION'
        ) THEN SUPPLIED_MATERIAL_V.LEGACY_FW_SUPPLIED_MATERIAL_NBR
    END AS LEGACY_CODE,
    CASE
        WHEN (
            SUPPLIED_MATERIAL_V.DIVISION_DESC = 'APPAREL DIVISION'
        ) THEN MATERIAL_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_V.PPS_ITEM_NBR
    END AS ITEM_NUMBER,
    (IFF(
                RTRIM(SUPPLIED_MATERIAL_V.MATERIAL_TYPE_4) =
                '', NULL,
                SUPPLIED_MATERIAL_V.MATERIAL_TYPE_4)) AS SUPPLIED_MATERIAL_TYPE_NAME,

    (IFF(
                RTRIM(SUPPLIED_MATERIAL_V.MATERIAL_TYPE_5) =
                '', NULL,
                SUPPLIED_MATERIAL_V.MATERIAL_TYPE_5)) AS SUPPLIED_MATERIAL_SUB_TYPE_NAME,

    (IFF(
                RTRIM(SUPPLIED_MATERIAL_V.MATERIAL_TYPE_6) =
                '', NULL,
                SUPPLIED_MATERIAL_V.MATERIAL_TYPE_6)) AS SUPPLIED_MATERIAL_SUB_TYPE_TWO_NAME,

    SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_ITEM_NM AS ITEM_NAME,
    SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_DESC AS ITEM_DESCRIPTION,
    --FND_MATERIAL.MATERIAL.ITEM_DESCRIPTION,
    SUPPLIED_MATERIAL_V.MATERIAL_FAMILY_NM AS FAMILY_NAME,
    SUPPLIED_MATERIAL_V.GRAMS_PER_THOUSAND_PIECES ,
    SUPPLIED_MATERIAL_V.WEIGHT_GRAMS_PER_SQUARE_METER AS GRAMS_PER_SQUARE_METER,
    SUPPLIED_MATERIAL_V.WIDTH_CM,
    SUPPLIED_MATERIAL_V.DIMENSION_WIDTH_INDICATOR_NM AS WIDTH_INDICATOR_NAME,
    SUPPLIED_MATERIAL_V.MATERIAL_NAME_VARIATION_WEIGHT_DESC AS WEIGHT_VARIATION_NAME,
    SUPPLIED_MATERIAL_V.ALL_PLYS_SAME_IND AS ALL_PLYS_SAME_INDICATOR,
    SUPPLIED_MATERIAL_ART_TECHNIQUE.ART_TECHNIQUE,
    SUPPLIED_MATERIAL_V.COMPONENT_CONSTRUCTION_TYPE_NM AS COMPONENT_CONSTRUCTION_TYPE,
    SUPPLIED_MATERIAL_V.HARD_OR_SOFT_COMPONENT_NM AS COMPONENT_HARD_SOFT,
    SUPPLIED_MATERIAL.ZIPPER_TEETH_TYPE_NAME,
    SUPPLIED_MATERIAL_V.ANIMAL_SOURCE_NM AS LEATHER_ANIMAL_SOURCE_NAME,
    SUPPLIED_MATERIAL_V.RE_TANNAGE_NM AS LEATHER_RE_TANNAGE_NAME,
    SUPPLIED_MATERIAL.LEGACY_MATERIAL_NAME,
    SUPPLIED_MATERIAL_V.METHOD_OF_MAKE_NM AS METHOD_OF_MAKE_NAME,
    SUPPLIED_MATERIAL_V.SCRIM_NM AS SCRIM_NAME,
    SUPPLIED_MATERIAL_V.NON_WOVEN_WEB_BONDING_METHOD_NM AS NON_WOVEN_WEB_BONDING_METHOD_NAME,
    SUPPLIED_MATERIAL_V.WEB_FORMATION_NM AS WEB_FORMATION_NAME,
    SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_STATE_NM AS STATE_NAME,
    SUPPLIED_MATERIAL_V.SUBSTRATE_CONSTRUCTION_NM AS SYNTHETIC_LEATHER_SUBSTRATE_CONSTRUCTION_NAME,
    SUPPLIED_MATERIAL_V.NON_WOVEN_SUBSTRATE_TYPE_NM AS NON_WOVEN_SUBSTRATE_TYPE_NAME,
    SUPPLIED_MATERIAL_V.TEXTILE_CONSTRUCTION_TYPE_NM AS TEXTILE_CONSTRUCTION_TYPE_NAME,
    SUPPLIED_MATERIAL_V.CLASSIFICATION_2 AS TEXTILE_SUB_VARIATION_NAME,
    SUPPLIED_MATERIAL_V.CLASSIFICATION_3 AS TEXTILE_SUB_VARIATION_TWO_NAME,
    SUPPLIED_MATERIAL_V.CLASSIFICATION_1 AS TEXTILE_VARIATION_NAME,
    SUPPLIED_MATERIAL_V.YARN_PLY_CNT AS YARN_PLY_COUNT,
    SUPPLIED_MATERIAL.YARN_AVERAGE_BODY_FIBER,
    SUPPLIED_MATERIAL.YARN_SMALLEST_BODY_FIBER,
    SUPPLIED_MATERIAL.YARN_LARGEST_BODY_FIBER,
    SUBSTRING(SUPPLIED_MATERIAL_V.INITIAL_SEASON_CYCLE_YEAR_DESC,3,4) AS INITIAL_SEASON_YEAR,
    SUBSTRING(SUPPLIED_MATERIAL_V.INITIAL_SEASON_CYCLE_YEAR_DESC,1,2) AS INITIAL_SEASON_CYCLE_CODE,
    SUPPLIED_MATERIAL.GRAMS_PER_LINEAR_METER,
    SUPPLIED_MATERIAL_V.PER_LINEAR_YARD_WEIGHT_GRAMS AS GRAMS_PER_LINEAR_YARD,
    SUPPLIED_MATERIAL_V.HEIGHT_CM,
    SUPPLIED_MATERIAL_V.HEIGHT_MM,
    SUPPLIED_MATERIAL_V.MATERIAL_LENGTH_CM AS LENGTH_CM,
    SUPPLIED_MATERIAL_V.MATERIAL_LENGTH_MM AS LENGTH_MM,
    SUPPLIED_MATERIAL_V.MATERIAL_MAXIMUM_THICKNESS_MM AS MAXIMUM_THICKNESS_MM,
    SUPPLIED_MATERIAL_V.MATERIAL_MINIMUM_THICKNESS_MM AS MINIMUM_THICKNESS_MM,
    SUPPLIED_MATERIAL.THICKNESS_MM,
    SUPPLIED_MATERIAL.THICKNESS_SELECTION,
    SUPPLIED_MATERIAL_V.WIDTH_MM,
    SUPPLIED_MATERIAL_V.END_USE_NM AS END_USE_NAME,
    MATERIAL.PARENT_MATERIAL_ID,
    -- PUBLISHED_MATERIAL_V.PARENT_MATERIAL_ID,  -- TODO: Resolve permission issue
    SUPPLIED_MATERIAL_V.DIVISION_DESC AS DIVISION_DESCRIPTION,
    SUPPLIED_MATERIAL_V.MATERIAL_CONTENT_SPECIFICATION_NBR AS MATERIAL_CONTENT_SPECIFICATION_NUMBER,
    (
        CASE
            WHEN RTRIM(
                SUPPLIED_MATERIAL_V.COMPLIANCE_ACCREDITATION_DESC
            ) = '' THEN NULL
            ELSE SUPPLIED_MATERIAL_V.COMPLIANCE_ACCREDITATION_DESC
        END
    ) AS COMPLIANCE_ACCREDITATION_DESCRIPTION
FROM MATERIAL_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_V
    -- TODO: Resolve permission issue
    -- LEFT OUTER JOIN MATERIAL_PROD.BCL_MATERIAL_LIBRARY.PUBLISHED_MATERIAL_V
    -- ON SUPPLIED_MATERIAL_V.MATERIAL_ID = PUBLISHED_MATERIAL_V.MATERIAL_ITEM_ID
    LEFT OUTER JOIN SUPPLIED_MATERIAL_ART_TECHNIQUE
    ON SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL_ART_TECHNIQUE.SUPPLIED_MATERIAL_ID
    LEFT OUTER JOIN FND_MATERIAL.SUPPLIED_MATERIAL
    ON SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL.SUPPLIED_MATERIAL_ID
    LEFT OUTER JOIN FND_MATERIAL.MATERIAL
    ON SUPPLIED_MATERIAL_V.MATERIAL_ID = MATERIAL.MATERIAL_ID
    LEFT OUTER JOIN SUPPLIED_MATERIAL_SUPPLIER
    ON SUPPLIED_MATERIAL_V.SUPPLIED_MATERIAL_ID = SUPPLIED_MATERIAL_SUPPLIER.SUPPLIED_MATERIAL_ID