
SELECT
    SUPPLIED_MATERIAL_ID,
	ROW_NUMBER() OVER(PARTITION BY SUPPLIED_MATERIAL_ID ORDER BY MATERIAL_CONTENT_PERCENTAGE DESC, MATERIAL_CONTENT_TYPE_NM DESC) as SUPPLIED_MATERIAL_CONTENT_ORDINAL,
	MATERIAL_CONTENT_TYPE_NM TYPE_NAME,
	MATERIAL_CONTENT_SOURCE_NM SOURCE_NAME,
    MATERIAL_CONTENT_PERCENTAGE/100 PERCENTAGE
FROM
    MATERIAL_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_CONTENT_V
