SELECT
    SUPPLIED_MATERIAL_ID,
    MATERIAL_TECHNOLOGIES_NM AS NAME
FROM MATERIALS_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_V
--A Simple filter on external team's object
WHERE NAME IS NOT NULL AND NAME != ''