SELECT 
SUPPLIED_MATERIAL_ID,
FINISH_PROCESS_NM AS NAME,
CASE WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL WATER REPELLENT-PFC-C4%%'  THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL DURABLE WATER RESISTANT %%' THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%(DWR)%%' THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL WATER REPELLENT-PFC-C6%%' THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL WATER REPELLENT%%' THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL WATERPROOF%%' THEN TRUE
WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%TREATMENT: CHEMICAL WATER REPELLENT-PFC-FREE %%' THEN TRUE
ELSE FALSE END AS DURABLE_WATER_RESISTANCE,
CASE WHEN UPPER(FINISH_PROCESS_NM) LIKE '%%PFC-FREE%%' THEN TRUE ELSE FALSE END AS PERFLUORINATED_COMPOUND_FREE
FROM (
    SELECT DISTINCT SUPPLIED_MATERIAL_ID, FINISH_PROCESS_NM
    FROM MATERIAL_PROD.BCL_MATERIAL_LIBRARY.SUPPLIED_MATERIAL_FINISH_V
    WHERE FINISH_PROCESS_NM IS NOT NULL 
) AS SUPPLIED_MATERIAL_FINISH